/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "./configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";

// Prefer Vite env VITE_API_URL, then REACT_APP_API_BASE, then localhost fallback.
// Using a small function keeps the generated file change small and predictable.
function getBasePath(): string {
  try {
    // @ts-ignore
    const v =
      typeof import.meta !== "undefined" &&
      (import.meta as any).env?.VITE_API_URL;
    if (v) return String(v).replace(/\/\/+$/, "");
  } catch {}
  try {
    const r = (globalThis as any)?.process?.env?.REACT_APP_API_BASE;
    if (r) return String(r).replace(/\/\/+$/, "");
  } catch {}
  return "http://localhost:8080";
}

export const BASE_PATH = getBasePath().replace(/\/\/+$/, "");

export const COLLECTION_FORMATS = {
  csv: ",",
  ssv: " ",
  tsv: "\t",
  pipes: "|",
};

export interface RequestArgs {
  url: string;
  options: RawAxiosRequestConfig;
}

export class BaseAPI {
  protected configuration: Configuration | undefined;

  constructor(
    configuration?: Configuration,
    protected basePath: string = BASE_PATH,
    protected axios: AxiosInstance = globalAxios,
  ) {
    if (configuration) {
      this.configuration = configuration;
      this.basePath = configuration.basePath ?? basePath;
    }
  }
}

export class RequiredError extends Error {
  constructor(
    public field: string,
    msg?: string,
  ) {
    super(msg);
    this.name = "RequiredError";
  }
}

interface ServerMap {
  [key: string]: {
    url: string;
    description: string;
  }[];
}

export const operationServerMap: ServerMap = {};
