/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseToken } from '../models';
/**
 * AdminGlobalApi - axios parameter creator
 */
export const AdminGlobalApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gerar token de acesso para qualquer usuário
         * @param {string} adminId 
         * @param {string} targetUserId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        impersonateUser: async (adminId: string, targetUserId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'adminId' is not null or undefined
            assertParamExists('impersonateUser', 'adminId', adminId)
            // verify required parameter 'targetUserId' is not null or undefined
            assertParamExists('impersonateUser', 'targetUserId', targetUserId)
            const localVarPath = `/api/v1/admin/impersonate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (adminId !== undefined) {
                localVarQueryParameter['adminId'] = adminId;
            }

            if (targetUserId !== undefined) {
                localVarQueryParameter['targetUserId'] = targetUserId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminGlobalApi - functional programming interface
 */
export const AdminGlobalApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminGlobalApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Gerar token de acesso para qualquer usuário
         * @param {string} adminId 
         * @param {string} targetUserId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async impersonateUser(adminId: string, targetUserId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseToken>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.impersonateUser(adminId, targetUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminGlobalApi.impersonateUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminGlobalApi - factory interface
 */
export const AdminGlobalApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminGlobalApiFp(configuration)
    return {
        /**
         * 
         * @summary Gerar token de acesso para qualquer usuário
         * @param {string} adminId 
         * @param {string} targetUserId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        impersonateUser(adminId: string, targetUserId: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseToken> {
            return localVarFp.impersonateUser(adminId, targetUserId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminGlobalApi - object-oriented interface
 */
export class AdminGlobalApi extends BaseAPI {
    /**
     * 
     * @summary Gerar token de acesso para qualquer usuário
     * @param {string} adminId 
     * @param {string} targetUserId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public impersonateUser(adminId: string, targetUserId: string, options?: RawAxiosRequestConfig) {
        return AdminGlobalApiFp(this.configuration).impersonateUser(adminId, targetUserId, options).then((request) => request(this.axios, this.basePath));
    }
}

