/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseAssinatura } from '../models';
// @ts-ignore
import type { AssinarPlanoRequest } from '../models';
/**
 * AssinaturasApi - axios parameter creator
 */
export const AssinaturasApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Inicia o fluxo de checkout ou altera o plano imediatamente se for upgrade gratuito/trial
         * @summary Contratar ou mudar de plano
         * @param {string} clinicaId 
         * @param {AssinarPlanoRequest} [assinarPlanoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assinarPlano: async (clinicaId: string, assinarPlanoRequest?: AssinarPlanoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clinicaId' is not null or undefined
            assertParamExists('assinarPlano', 'clinicaId', clinicaId)
            const localVarPath = `/api/v1/saas/assinar`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (clinicaId !== undefined) {
                localVarQueryParameter['clinicaId'] = clinicaId;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(assinarPlanoRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Obter status da assinatura da clínica logada
         * @param {string} clinicaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        obterMinhaAssinatura: async (clinicaId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clinicaId' is not null or undefined
            assertParamExists('obterMinhaAssinatura', 'clinicaId', clinicaId)
            const localVarPath = `/api/v1/saas/minha-assinatura`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (clinicaId !== undefined) {
                localVarQueryParameter['clinicaId'] = clinicaId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AssinaturasApi - functional programming interface
 */
export const AssinaturasApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AssinaturasApiAxiosParamCreator(configuration)
    return {
        /**
         * Inicia o fluxo de checkout ou altera o plano imediatamente se for upgrade gratuito/trial
         * @summary Contratar ou mudar de plano
         * @param {string} clinicaId 
         * @param {AssinarPlanoRequest} [assinarPlanoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async assinarPlano(clinicaId: string, assinarPlanoRequest?: AssinarPlanoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseAssinatura>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.assinarPlano(clinicaId, assinarPlanoRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AssinaturasApi.assinarPlano']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Obter status da assinatura da clínica logada
         * @param {string} clinicaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async obterMinhaAssinatura(clinicaId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseAssinatura>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.obterMinhaAssinatura(clinicaId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AssinaturasApi.obterMinhaAssinatura']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AssinaturasApi - factory interface
 */
export const AssinaturasApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AssinaturasApiFp(configuration)
    return {
        /**
         * Inicia o fluxo de checkout ou altera o plano imediatamente se for upgrade gratuito/trial
         * @summary Contratar ou mudar de plano
         * @param {string} clinicaId 
         * @param {AssinarPlanoRequest} [assinarPlanoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assinarPlano(clinicaId: string, assinarPlanoRequest?: AssinarPlanoRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseAssinatura> {
            return localVarFp.assinarPlano(clinicaId, assinarPlanoRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Obter status da assinatura da clínica logada
         * @param {string} clinicaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        obterMinhaAssinatura(clinicaId: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseAssinatura> {
            return localVarFp.obterMinhaAssinatura(clinicaId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AssinaturasApi - object-oriented interface
 */
export class AssinaturasApi extends BaseAPI {
    /**
     * Inicia o fluxo de checkout ou altera o plano imediatamente se for upgrade gratuito/trial
     * @summary Contratar ou mudar de plano
     * @param {string} clinicaId 
     * @param {AssinarPlanoRequest} [assinarPlanoRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public assinarPlano(clinicaId: string, assinarPlanoRequest?: AssinarPlanoRequest, options?: RawAxiosRequestConfig) {
        return AssinaturasApiFp(this.configuration).assinarPlano(clinicaId, assinarPlanoRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Obter status da assinatura da clínica logada
     * @param {string} clinicaId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public obterMinhaAssinatura(clinicaId: string, options?: RawAxiosRequestConfig) {
        return AssinaturasApiFp(this.configuration).obterMinhaAssinatura(clinicaId, options).then((request) => request(this.axios, this.basePath));
    }
}

