/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AgendamentoRequest } from '../models';
// @ts-ignore
import type { ApiResponseAtendimento } from '../models';
// @ts-ignore
import type { ApiResponseListaAtendimento } from '../models';
// @ts-ignore
import type { AtendimentoRequest } from '../models';
// @ts-ignore
import type { AtualizarStatusAtendimentoRequest } from '../models';
// @ts-ignore
import type { FinalizacaoAtendimentoRequest } from '../models';
/**
 * AtendimentosApi - axios parameter creator
 */
export const AtendimentosApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Cria um registro com status AGENDADO. Dados clínicos não são permitidos aqui.
         * @summary Agendar novo atendimento
         * @param {AgendamentoRequest} [agendamentoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agendarAtendimento: async (agendamentoRequest?: AgendamentoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/atendimentos/agendar`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(agendamentoRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Atualizar (Evoluir status, adicionar obs)
         * @param {string} id 
         * @param {AtendimentoRequest} [atendimentoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarAtendimento: async (id: string, atendimentoRequest?: AtendimentoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('atualizarAtendimento', 'id', id)
            const localVarPath = `/api/v1/atendimentos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(atendimentoRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Alterar status do atendimento
         * @param {string} id 
         * @param {AtualizarStatusAtendimentoRequest} [atualizarStatusAtendimentoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarStatusAtendimento: async (id: string, atualizarStatusAtendimentoRequest?: AtualizarStatusAtendimentoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('atualizarStatusAtendimento', 'id', id)
            const localVarPath = `/api/v1/atendimentos/{id}/status`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(atualizarStatusAtendimentoRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Ver detalhes
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarAtendimentoPorId: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('buscarAtendimentoPorId', 'id', id)
            const localVarPath = `/api/v1/atendimentos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Registrar atendimento completo (Legado)
         * @param {AtendimentoRequest} [atendimentoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarAtendimento: async (atendimentoRequest?: AtendimentoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/atendimentos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(atendimentoRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Recebe os dados clínicos e muda status para REALIZADO
         * @summary Finalizar atendimento (Preencher Prontuário)
         * @param {string} id 
         * @param {FinalizacaoAtendimentoRequest} [finalizacaoAtendimentoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finalizarAtendimento: async (id: string, finalizacaoAtendimentoRequest?: FinalizacaoAtendimentoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('finalizarAtendimento', 'id', id)
            const localVarPath = `/api/v1/atendimentos/{id}/finalizar`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(finalizacaoAtendimentoRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Histórico clínico do paciente
         * @param {string} pacienteId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarAtendimentosPorPaciente: async (pacienteId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pacienteId' is not null or undefined
            assertParamExists('listarAtendimentosPorPaciente', 'pacienteId', pacienteId)
            const localVarPath = `/api/v1/pacientes/{pacienteId}/atendimentos`
                .replace(`{${"pacienteId"}}`, encodeURIComponent(String(pacienteId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Listar meus atendimentos (Agenda)
         * @param {string} veterinarioId 
         * @param {ListarMeusAtendimentosStatusEnum} [status] 
         * @param {string} [pacienteId] 
         * @param {string} [dataInicio] 
         * @param {string} [dataFim] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarMeusAtendimentos: async (veterinarioId: string, status?: ListarMeusAtendimentosStatusEnum, pacienteId?: string, dataInicio?: string, dataFim?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'veterinarioId' is not null or undefined
            assertParamExists('listarMeusAtendimentos', 'veterinarioId', veterinarioId)
            const localVarPath = `/api/v1/atendimentos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (veterinarioId !== undefined) {
                localVarQueryParameter['veterinarioId'] = veterinarioId;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (pacienteId !== undefined) {
                localVarQueryParameter['pacienteId'] = pacienteId;
            }

            if (dataInicio !== undefined) {
                localVarQueryParameter['dataInicio'] = (dataInicio as any instanceof Date) ?
                    (dataInicio as any).toISOString().substring(0,10) :
                    dataInicio;
            }

            if (dataFim !== undefined) {
                localVarQueryParameter['dataFim'] = (dataFim as any instanceof Date) ?
                    (dataFim as any).toISOString().substring(0,10) :
                    dataFim;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AtendimentosApi - functional programming interface
 */
export const AtendimentosApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AtendimentosApiAxiosParamCreator(configuration)
    return {
        /**
         * Cria um registro com status AGENDADO. Dados clínicos não são permitidos aqui.
         * @summary Agendar novo atendimento
         * @param {AgendamentoRequest} [agendamentoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agendarAtendimento(agendamentoRequest?: AgendamentoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseAtendimento>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agendarAtendimento(agendamentoRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AtendimentosApi.agendarAtendimento']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Atualizar (Evoluir status, adicionar obs)
         * @param {string} id 
         * @param {AtendimentoRequest} [atendimentoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async atualizarAtendimento(id: string, atendimentoRequest?: AtendimentoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseAtendimento>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.atualizarAtendimento(id, atendimentoRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AtendimentosApi.atualizarAtendimento']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Alterar status do atendimento
         * @param {string} id 
         * @param {AtualizarStatusAtendimentoRequest} [atualizarStatusAtendimentoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async atualizarStatusAtendimento(id: string, atualizarStatusAtendimentoRequest?: AtualizarStatusAtendimentoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseAtendimento>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.atualizarStatusAtendimento(id, atualizarStatusAtendimentoRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AtendimentosApi.atualizarStatusAtendimento']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Ver detalhes
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async buscarAtendimentoPorId(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseAtendimento>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.buscarAtendimentoPorId(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AtendimentosApi.buscarAtendimentoPorId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Registrar atendimento completo (Legado)
         * @param {AtendimentoRequest} [atendimentoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async criarAtendimento(atendimentoRequest?: AtendimentoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseAtendimento>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.criarAtendimento(atendimentoRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AtendimentosApi.criarAtendimento']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Recebe os dados clínicos e muda status para REALIZADO
         * @summary Finalizar atendimento (Preencher Prontuário)
         * @param {string} id 
         * @param {FinalizacaoAtendimentoRequest} [finalizacaoAtendimentoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async finalizarAtendimento(id: string, finalizacaoAtendimentoRequest?: FinalizacaoAtendimentoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseAtendimento>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.finalizarAtendimento(id, finalizacaoAtendimentoRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AtendimentosApi.finalizarAtendimento']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Histórico clínico do paciente
         * @param {string} pacienteId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listarAtendimentosPorPaciente(pacienteId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListaAtendimento>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listarAtendimentosPorPaciente(pacienteId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AtendimentosApi.listarAtendimentosPorPaciente']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Listar meus atendimentos (Agenda)
         * @param {string} veterinarioId 
         * @param {ListarMeusAtendimentosStatusEnum} [status] 
         * @param {string} [pacienteId] 
         * @param {string} [dataInicio] 
         * @param {string} [dataFim] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listarMeusAtendimentos(veterinarioId: string, status?: ListarMeusAtendimentosStatusEnum, pacienteId?: string, dataInicio?: string, dataFim?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListaAtendimento>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listarMeusAtendimentos(veterinarioId, status, pacienteId, dataInicio, dataFim, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AtendimentosApi.listarMeusAtendimentos']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AtendimentosApi - factory interface
 */
export const AtendimentosApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AtendimentosApiFp(configuration)
    return {
        /**
         * Cria um registro com status AGENDADO. Dados clínicos não são permitidos aqui.
         * @summary Agendar novo atendimento
         * @param {AgendamentoRequest} [agendamentoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agendarAtendimento(agendamentoRequest?: AgendamentoRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseAtendimento> {
            return localVarFp.agendarAtendimento(agendamentoRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Atualizar (Evoluir status, adicionar obs)
         * @param {string} id 
         * @param {AtendimentoRequest} [atendimentoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarAtendimento(id: string, atendimentoRequest?: AtendimentoRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseAtendimento> {
            return localVarFp.atualizarAtendimento(id, atendimentoRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Alterar status do atendimento
         * @param {string} id 
         * @param {AtualizarStatusAtendimentoRequest} [atualizarStatusAtendimentoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarStatusAtendimento(id: string, atualizarStatusAtendimentoRequest?: AtualizarStatusAtendimentoRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseAtendimento> {
            return localVarFp.atualizarStatusAtendimento(id, atualizarStatusAtendimentoRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Ver detalhes
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarAtendimentoPorId(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseAtendimento> {
            return localVarFp.buscarAtendimentoPorId(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Registrar atendimento completo (Legado)
         * @param {AtendimentoRequest} [atendimentoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarAtendimento(atendimentoRequest?: AtendimentoRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseAtendimento> {
            return localVarFp.criarAtendimento(atendimentoRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Recebe os dados clínicos e muda status para REALIZADO
         * @summary Finalizar atendimento (Preencher Prontuário)
         * @param {string} id 
         * @param {FinalizacaoAtendimentoRequest} [finalizacaoAtendimentoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finalizarAtendimento(id: string, finalizacaoAtendimentoRequest?: FinalizacaoAtendimentoRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseAtendimento> {
            return localVarFp.finalizarAtendimento(id, finalizacaoAtendimentoRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Histórico clínico do paciente
         * @param {string} pacienteId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarAtendimentosPorPaciente(pacienteId: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListaAtendimento> {
            return localVarFp.listarAtendimentosPorPaciente(pacienteId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Listar meus atendimentos (Agenda)
         * @param {string} veterinarioId 
         * @param {ListarMeusAtendimentosStatusEnum} [status] 
         * @param {string} [pacienteId] 
         * @param {string} [dataInicio] 
         * @param {string} [dataFim] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarMeusAtendimentos(veterinarioId: string, status?: ListarMeusAtendimentosStatusEnum, pacienteId?: string, dataInicio?: string, dataFim?: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListaAtendimento> {
            return localVarFp.listarMeusAtendimentos(veterinarioId, status, pacienteId, dataInicio, dataFim, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AtendimentosApi - object-oriented interface
 */
export class AtendimentosApi extends BaseAPI {
    /**
     * Cria um registro com status AGENDADO. Dados clínicos não são permitidos aqui.
     * @summary Agendar novo atendimento
     * @param {AgendamentoRequest} [agendamentoRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public agendarAtendimento(agendamentoRequest?: AgendamentoRequest, options?: RawAxiosRequestConfig) {
        return AtendimentosApiFp(this.configuration).agendarAtendimento(agendamentoRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Atualizar (Evoluir status, adicionar obs)
     * @param {string} id 
     * @param {AtendimentoRequest} [atendimentoRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public atualizarAtendimento(id: string, atendimentoRequest?: AtendimentoRequest, options?: RawAxiosRequestConfig) {
        return AtendimentosApiFp(this.configuration).atualizarAtendimento(id, atendimentoRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Alterar status do atendimento
     * @param {string} id 
     * @param {AtualizarStatusAtendimentoRequest} [atualizarStatusAtendimentoRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public atualizarStatusAtendimento(id: string, atualizarStatusAtendimentoRequest?: AtualizarStatusAtendimentoRequest, options?: RawAxiosRequestConfig) {
        return AtendimentosApiFp(this.configuration).atualizarStatusAtendimento(id, atualizarStatusAtendimentoRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Ver detalhes
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public buscarAtendimentoPorId(id: string, options?: RawAxiosRequestConfig) {
        return AtendimentosApiFp(this.configuration).buscarAtendimentoPorId(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Registrar atendimento completo (Legado)
     * @param {AtendimentoRequest} [atendimentoRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public criarAtendimento(atendimentoRequest?: AtendimentoRequest, options?: RawAxiosRequestConfig) {
        return AtendimentosApiFp(this.configuration).criarAtendimento(atendimentoRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Recebe os dados clínicos e muda status para REALIZADO
     * @summary Finalizar atendimento (Preencher Prontuário)
     * @param {string} id 
     * @param {FinalizacaoAtendimentoRequest} [finalizacaoAtendimentoRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public finalizarAtendimento(id: string, finalizacaoAtendimentoRequest?: FinalizacaoAtendimentoRequest, options?: RawAxiosRequestConfig) {
        return AtendimentosApiFp(this.configuration).finalizarAtendimento(id, finalizacaoAtendimentoRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Histórico clínico do paciente
     * @param {string} pacienteId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listarAtendimentosPorPaciente(pacienteId: string, options?: RawAxiosRequestConfig) {
        return AtendimentosApiFp(this.configuration).listarAtendimentosPorPaciente(pacienteId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Listar meus atendimentos (Agenda)
     * @param {string} veterinarioId 
     * @param {ListarMeusAtendimentosStatusEnum} [status] 
     * @param {string} [pacienteId] 
     * @param {string} [dataInicio] 
     * @param {string} [dataFim] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listarMeusAtendimentos(veterinarioId: string, status?: ListarMeusAtendimentosStatusEnum, pacienteId?: string, dataInicio?: string, dataFim?: string, options?: RawAxiosRequestConfig) {
        return AtendimentosApiFp(this.configuration).listarMeusAtendimentos(veterinarioId, status, pacienteId, dataInicio, dataFim, options).then((request) => request(this.axios, this.basePath));
    }
}

export const ListarMeusAtendimentosStatusEnum = {
    Agendado: 'AGENDADO',
    EmAndamento: 'EM_ANDAMENTO',
    Realizado: 'REALIZADO',
    Cancelado: 'CANCELADO'
} as const;
export type ListarMeusAtendimentosStatusEnum = typeof ListarMeusAtendimentosStatusEnum[keyof typeof ListarMeusAtendimentosStatusEnum];
