/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseListaAuditoria } from '../models';
// @ts-ignore
import type { ApiResponseSucesso } from '../models';
// @ts-ignore
import type { EventoAuditoriaRequest } from '../models';
/**
 * AuditoriaApi - axios parameter creator
 */
export const AuditoriaApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Listar logs de auditoria da clínica
         * @param {string} clinicaId 
         * @param {string} [dataInicio] 
         * @param {string} [dataFim] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarLogsAuditoria: async (clinicaId: string, dataInicio?: string, dataFim?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clinicaId' is not null or undefined
            assertParamExists('listarLogsAuditoria', 'clinicaId', clinicaId)
            const localVarPath = `/api/v1/auditoria`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (clinicaId !== undefined) {
                localVarQueryParameter['clinicaId'] = clinicaId;
            }

            if (dataInicio !== undefined) {
                localVarQueryParameter['dataInicio'] = (dataInicio as any instanceof Date) ?
                    (dataInicio as any).toISOString().substring(0,10) :
                    dataInicio;
            }

            if (dataFim !== undefined) {
                localVarQueryParameter['dataFim'] = (dataFim as any instanceof Date) ?
                    (dataFim as any).toISOString().substring(0,10) :
                    dataFim;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Registrar evento de frontend
         * @param {EventoAuditoriaRequest} [eventoAuditoriaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registrarEventoAuditoria: async (eventoAuditoriaRequest?: EventoAuditoriaRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/auditoria/evento`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(eventoAuditoriaRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuditoriaApi - functional programming interface
 */
export const AuditoriaApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuditoriaApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Listar logs de auditoria da clínica
         * @param {string} clinicaId 
         * @param {string} [dataInicio] 
         * @param {string} [dataFim] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listarLogsAuditoria(clinicaId: string, dataInicio?: string, dataFim?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListaAuditoria>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listarLogsAuditoria(clinicaId, dataInicio, dataFim, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuditoriaApi.listarLogsAuditoria']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Registrar evento de frontend
         * @param {EventoAuditoriaRequest} [eventoAuditoriaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registrarEventoAuditoria(eventoAuditoriaRequest?: EventoAuditoriaRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseSucesso>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registrarEventoAuditoria(eventoAuditoriaRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuditoriaApi.registrarEventoAuditoria']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuditoriaApi - factory interface
 */
export const AuditoriaApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuditoriaApiFp(configuration)
    return {
        /**
         * 
         * @summary Listar logs de auditoria da clínica
         * @param {string} clinicaId 
         * @param {string} [dataInicio] 
         * @param {string} [dataFim] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarLogsAuditoria(clinicaId: string, dataInicio?: string, dataFim?: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListaAuditoria> {
            return localVarFp.listarLogsAuditoria(clinicaId, dataInicio, dataFim, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Registrar evento de frontend
         * @param {EventoAuditoriaRequest} [eventoAuditoriaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registrarEventoAuditoria(eventoAuditoriaRequest?: EventoAuditoriaRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseSucesso> {
            return localVarFp.registrarEventoAuditoria(eventoAuditoriaRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuditoriaApi - object-oriented interface
 */
export class AuditoriaApi extends BaseAPI {
    /**
     * 
     * @summary Listar logs de auditoria da clínica
     * @param {string} clinicaId 
     * @param {string} [dataInicio] 
     * @param {string} [dataFim] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listarLogsAuditoria(clinicaId: string, dataInicio?: string, dataFim?: string, options?: RawAxiosRequestConfig) {
        return AuditoriaApiFp(this.configuration).listarLogsAuditoria(clinicaId, dataInicio, dataFim, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Registrar evento de frontend
     * @param {EventoAuditoriaRequest} [eventoAuditoriaRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public registrarEventoAuditoria(eventoAuditoriaRequest?: EventoAuditoriaRequest, options?: RawAxiosRequestConfig) {
        return AuditoriaApiFp(this.configuration).registrarEventoAuditoria(eventoAuditoriaRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

