/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseCalculo } from '../models';
// @ts-ignore
import type { CalculoCatalogoRequest } from '../models';
// @ts-ignore
import type { CalculoLivreRequest } from '../models';
// @ts-ignore
import type { CalculoSeguroRequest } from '../models';
/**
 * CalculadoraApi - axios parameter creator
 */
export const CalculadoraApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Calcular via Protocolo
         * @param {CalculoSeguroRequest} [calculoSeguroRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calcularDosagemSegura: async (calculoSeguroRequest?: CalculoSeguroRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/calculadora/dosagem`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(calculoSeguroRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Faz apenas o cálculo matemático de volume com base na dose e concentração informadas.
         * @summary Calculadora Livre (Sem Validação)
         * @param {CalculoLivreRequest} [calculoLivreRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calcularDoseLivre: async (calculoLivreRequest?: CalculoLivreRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/calculadora/livre`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(calculoLivreRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Verifica se a dose está segura cruzando com a base científica.
         * @summary Validar Dose (Catálogo)
         * @param {CalculoCatalogoRequest} [calculoCatalogoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validarDoseCatalogo: async (calculoCatalogoRequest?: CalculoCatalogoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/calculadora/validar`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(calculoCatalogoRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CalculadoraApi - functional programming interface
 */
export const CalculadoraApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CalculadoraApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Calcular via Protocolo
         * @param {CalculoSeguroRequest} [calculoSeguroRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calcularDosagemSegura(calculoSeguroRequest?: CalculoSeguroRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseCalculo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.calcularDosagemSegura(calculoSeguroRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CalculadoraApi.calcularDosagemSegura']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Faz apenas o cálculo matemático de volume com base na dose e concentração informadas.
         * @summary Calculadora Livre (Sem Validação)
         * @param {CalculoLivreRequest} [calculoLivreRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calcularDoseLivre(calculoLivreRequest?: CalculoLivreRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseCalculo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.calcularDoseLivre(calculoLivreRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CalculadoraApi.calcularDoseLivre']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Verifica se a dose está segura cruzando com a base científica.
         * @summary Validar Dose (Catálogo)
         * @param {CalculoCatalogoRequest} [calculoCatalogoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validarDoseCatalogo(calculoCatalogoRequest?: CalculoCatalogoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseCalculo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.validarDoseCatalogo(calculoCatalogoRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CalculadoraApi.validarDoseCatalogo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CalculadoraApi - factory interface
 */
export const CalculadoraApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CalculadoraApiFp(configuration)
    return {
        /**
         * 
         * @summary Calcular via Protocolo
         * @param {CalculoSeguroRequest} [calculoSeguroRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calcularDosagemSegura(calculoSeguroRequest?: CalculoSeguroRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseCalculo> {
            return localVarFp.calcularDosagemSegura(calculoSeguroRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Faz apenas o cálculo matemático de volume com base na dose e concentração informadas.
         * @summary Calculadora Livre (Sem Validação)
         * @param {CalculoLivreRequest} [calculoLivreRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calcularDoseLivre(calculoLivreRequest?: CalculoLivreRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseCalculo> {
            return localVarFp.calcularDoseLivre(calculoLivreRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Verifica se a dose está segura cruzando com a base científica.
         * @summary Validar Dose (Catálogo)
         * @param {CalculoCatalogoRequest} [calculoCatalogoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validarDoseCatalogo(calculoCatalogoRequest?: CalculoCatalogoRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseCalculo> {
            return localVarFp.validarDoseCatalogo(calculoCatalogoRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CalculadoraApi - object-oriented interface
 */
export class CalculadoraApi extends BaseAPI {
    /**
     * 
     * @summary Calcular via Protocolo
     * @param {CalculoSeguroRequest} [calculoSeguroRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public calcularDosagemSegura(calculoSeguroRequest?: CalculoSeguroRequest, options?: RawAxiosRequestConfig) {
        return CalculadoraApiFp(this.configuration).calcularDosagemSegura(calculoSeguroRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Faz apenas o cálculo matemático de volume com base na dose e concentração informadas.
     * @summary Calculadora Livre (Sem Validação)
     * @param {CalculoLivreRequest} [calculoLivreRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public calcularDoseLivre(calculoLivreRequest?: CalculoLivreRequest, options?: RawAxiosRequestConfig) {
        return CalculadoraApiFp(this.configuration).calcularDoseLivre(calculoLivreRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Verifica se a dose está segura cruzando com a base científica.
     * @summary Validar Dose (Catálogo)
     * @param {CalculoCatalogoRequest} [calculoCatalogoRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public validarDoseCatalogo(calculoCatalogoRequest?: CalculoCatalogoRequest, options?: RawAxiosRequestConfig) {
        return CalculadoraApiFp(this.configuration).validarDoseCatalogo(calculoCatalogoRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

