/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseContraindicacao } from '../models';
// @ts-ignore
import type { ApiResponseListaContraindicacao } from '../models';
// @ts-ignore
import type { ContraindicacaoRequest } from '../models';
/**
 * ContraindicacoesApi - axios parameter creator
 */
export const ContraindicacoesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Atualizar
         * @param {string} id 
         * @param {ContraindicacaoRequest} [contraindicacaoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarContraindicacao: async (id: string, contraindicacaoRequest?: ContraindicacaoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('atualizarContraindicacao', 'id', id)
            const localVarPath = `/api/v1/contraindicacoes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(contraindicacaoRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Buscar por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarContraindicacaoPorId: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('buscarContraindicacaoPorId', 'id', id)
            const localVarPath = `/api/v1/contraindicacoes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Cadastrar contraindicação
         * @param {ContraindicacaoRequest} [contraindicacaoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarContraindicacao: async (contraindicacaoRequest?: ContraindicacaoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/contraindicacoes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(contraindicacaoRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Remover
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarContraindicacao: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletarContraindicacao', 'id', id)
            const localVarPath = `/api/v1/contraindicacoes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Listar contraindicações de um medicamento
         * @param {string} medicamentoId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarContraindicacoesPorMedicamento: async (medicamentoId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'medicamentoId' is not null or undefined
            assertParamExists('listarContraindicacoesPorMedicamento', 'medicamentoId', medicamentoId)
            const localVarPath = `/api/v1/medicamentos/{medicamentoId}/contraindicacoes`
                .replace(`{${"medicamentoId"}}`, encodeURIComponent(String(medicamentoId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ContraindicacoesApi - functional programming interface
 */
export const ContraindicacoesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ContraindicacoesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Atualizar
         * @param {string} id 
         * @param {ContraindicacaoRequest} [contraindicacaoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async atualizarContraindicacao(id: string, contraindicacaoRequest?: ContraindicacaoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseContraindicacao>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.atualizarContraindicacao(id, contraindicacaoRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContraindicacoesApi.atualizarContraindicacao']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Buscar por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async buscarContraindicacaoPorId(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseContraindicacao>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.buscarContraindicacaoPorId(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContraindicacoesApi.buscarContraindicacaoPorId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Cadastrar contraindicação
         * @param {ContraindicacaoRequest} [contraindicacaoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async criarContraindicacao(contraindicacaoRequest?: ContraindicacaoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseContraindicacao>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.criarContraindicacao(contraindicacaoRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContraindicacoesApi.criarContraindicacao']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Remover
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletarContraindicacao(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletarContraindicacao(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContraindicacoesApi.deletarContraindicacao']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Listar contraindicações de um medicamento
         * @param {string} medicamentoId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listarContraindicacoesPorMedicamento(medicamentoId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListaContraindicacao>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listarContraindicacoesPorMedicamento(medicamentoId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContraindicacoesApi.listarContraindicacoesPorMedicamento']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ContraindicacoesApi - factory interface
 */
export const ContraindicacoesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ContraindicacoesApiFp(configuration)
    return {
        /**
         * 
         * @summary Atualizar
         * @param {string} id 
         * @param {ContraindicacaoRequest} [contraindicacaoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarContraindicacao(id: string, contraindicacaoRequest?: ContraindicacaoRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseContraindicacao> {
            return localVarFp.atualizarContraindicacao(id, contraindicacaoRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Buscar por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarContraindicacaoPorId(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseContraindicacao> {
            return localVarFp.buscarContraindicacaoPorId(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Cadastrar contraindicação
         * @param {ContraindicacaoRequest} [contraindicacaoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarContraindicacao(contraindicacaoRequest?: ContraindicacaoRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseContraindicacao> {
            return localVarFp.criarContraindicacao(contraindicacaoRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Remover
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarContraindicacao(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deletarContraindicacao(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Listar contraindicações de um medicamento
         * @param {string} medicamentoId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarContraindicacoesPorMedicamento(medicamentoId: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListaContraindicacao> {
            return localVarFp.listarContraindicacoesPorMedicamento(medicamentoId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ContraindicacoesApi - object-oriented interface
 */
export class ContraindicacoesApi extends BaseAPI {
    /**
     * 
     * @summary Atualizar
     * @param {string} id 
     * @param {ContraindicacaoRequest} [contraindicacaoRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public atualizarContraindicacao(id: string, contraindicacaoRequest?: ContraindicacaoRequest, options?: RawAxiosRequestConfig) {
        return ContraindicacoesApiFp(this.configuration).atualizarContraindicacao(id, contraindicacaoRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Buscar por ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public buscarContraindicacaoPorId(id: string, options?: RawAxiosRequestConfig) {
        return ContraindicacoesApiFp(this.configuration).buscarContraindicacaoPorId(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Cadastrar contraindicação
     * @param {ContraindicacaoRequest} [contraindicacaoRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public criarContraindicacao(contraindicacaoRequest?: ContraindicacaoRequest, options?: RawAxiosRequestConfig) {
        return ContraindicacoesApiFp(this.configuration).criarContraindicacao(contraindicacaoRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Remover
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletarContraindicacao(id: string, options?: RawAxiosRequestConfig) {
        return ContraindicacoesApiFp(this.configuration).deletarContraindicacao(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Listar contraindicações de um medicamento
     * @param {string} medicamentoId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listarContraindicacoesPorMedicamento(medicamentoId: string, options?: RawAxiosRequestConfig) {
        return ContraindicacoesApiFp(this.configuration).listarContraindicacoesPorMedicamento(medicamentoId, options).then((request) => request(this.axios, this.basePath));
    }
}

