/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseDoenca } from '../models';
// @ts-ignore
import type { ApiResponseListaDoenca } from '../models';
// @ts-ignore
import type { DoencaRequest } from '../models';
/**
 * DoencasApi - axios parameter creator
 */
export const DoencasApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Atualizar doença
         * @param {string} id 
         * @param {DoencaRequest} [doencaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarDoenca: async (id: string, doencaRequest?: DoencaRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('atualizarDoenca', 'id', id)
            const localVarPath = `/api/v1/doencas/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(doencaRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Buscar doença por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarDoencaPorId: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('buscarDoencaPorId', 'id', id)
            const localVarPath = `/api/v1/doencas/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Cadastrar nova doença
         * @param {DoencaRequest} [doencaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarDoenca: async (doencaRequest?: DoencaRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/doencas`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(doencaRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Remover doença
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarDoenca: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletarDoenca', 'id', id)
            const localVarPath = `/api/v1/doencas/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Listar todas as doenças
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarDoencas: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/doencas`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Listar doenças de uma espécie específica
         * @param {string} especieId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarDoencasPorEspecie: async (especieId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'especieId' is not null or undefined
            assertParamExists('listarDoencasPorEspecie', 'especieId', especieId)
            const localVarPath = `/api/v1/doencas/por-especie/{especieId}`
                .replace(`{${"especieId"}}`, encodeURIComponent(String(especieId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DoencasApi - functional programming interface
 */
export const DoencasApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DoencasApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Atualizar doença
         * @param {string} id 
         * @param {DoencaRequest} [doencaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async atualizarDoenca(id: string, doencaRequest?: DoencaRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseDoenca>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.atualizarDoenca(id, doencaRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DoencasApi.atualizarDoenca']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Buscar doença por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async buscarDoencaPorId(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseDoenca>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.buscarDoencaPorId(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DoencasApi.buscarDoencaPorId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Cadastrar nova doença
         * @param {DoencaRequest} [doencaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async criarDoenca(doencaRequest?: DoencaRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseDoenca>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.criarDoenca(doencaRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DoencasApi.criarDoenca']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Remover doença
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletarDoenca(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletarDoenca(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DoencasApi.deletarDoenca']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Listar todas as doenças
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listarDoencas(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListaDoenca>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listarDoencas(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DoencasApi.listarDoencas']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Listar doenças de uma espécie específica
         * @param {string} especieId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listarDoencasPorEspecie(especieId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListaDoenca>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listarDoencasPorEspecie(especieId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DoencasApi.listarDoencasPorEspecie']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DoencasApi - factory interface
 */
export const DoencasApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DoencasApiFp(configuration)
    return {
        /**
         * 
         * @summary Atualizar doença
         * @param {string} id 
         * @param {DoencaRequest} [doencaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarDoenca(id: string, doencaRequest?: DoencaRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseDoenca> {
            return localVarFp.atualizarDoenca(id, doencaRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Buscar doença por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarDoencaPorId(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseDoenca> {
            return localVarFp.buscarDoencaPorId(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Cadastrar nova doença
         * @param {DoencaRequest} [doencaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarDoenca(doencaRequest?: DoencaRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseDoenca> {
            return localVarFp.criarDoenca(doencaRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Remover doença
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarDoenca(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deletarDoenca(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Listar todas as doenças
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarDoencas(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListaDoenca> {
            return localVarFp.listarDoencas(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Listar doenças de uma espécie específica
         * @param {string} especieId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarDoencasPorEspecie(especieId: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListaDoenca> {
            return localVarFp.listarDoencasPorEspecie(especieId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DoencasApi - object-oriented interface
 */
export class DoencasApi extends BaseAPI {
    /**
     * 
     * @summary Atualizar doença
     * @param {string} id 
     * @param {DoencaRequest} [doencaRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public atualizarDoenca(id: string, doencaRequest?: DoencaRequest, options?: RawAxiosRequestConfig) {
        return DoencasApiFp(this.configuration).atualizarDoenca(id, doencaRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Buscar doença por ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public buscarDoencaPorId(id: string, options?: RawAxiosRequestConfig) {
        return DoencasApiFp(this.configuration).buscarDoencaPorId(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Cadastrar nova doença
     * @param {DoencaRequest} [doencaRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public criarDoenca(doencaRequest?: DoencaRequest, options?: RawAxiosRequestConfig) {
        return DoencasApiFp(this.configuration).criarDoenca(doencaRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Remover doença
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletarDoenca(id: string, options?: RawAxiosRequestConfig) {
        return DoencasApiFp(this.configuration).deletarDoenca(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Listar todas as doenças
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listarDoencas(options?: RawAxiosRequestConfig) {
        return DoencasApiFp(this.configuration).listarDoencas(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Listar doenças de uma espécie específica
     * @param {string} especieId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listarDoencasPorEspecie(especieId: string, options?: RawAxiosRequestConfig) {
        return DoencasApiFp(this.configuration).listarDoencasPorEspecie(especieId, options).then((request) => request(this.axios, this.basePath));
    }
}

