/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseEspecie } from '../models';
// @ts-ignore
import type { ApiResponseListaEspecie } from '../models';
// @ts-ignore
import type { EspecieRequest } from '../models';
/**
 * EspeciesApi - axios parameter creator
 */
export const EspeciesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Atualizar dados da espécie
         * @param {string} id 
         * @param {EspecieRequest} [especieRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarEspecie: async (id: string, especieRequest?: EspecieRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('atualizarEspecie', 'id', id)
            const localVarPath = `/api/v1/especies/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(especieRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Buscar espécie por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarEspeciePorId: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('buscarEspeciePorId', 'id', id)
            const localVarPath = `/api/v1/especies/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Cadastrar nova espécie
         * @param {EspecieRequest} [especieRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarEspecie: async (especieRequest?: EspecieRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/especies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(especieRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Remover espécie
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarEspecie: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletarEspecie', 'id', id)
            const localVarPath = `/api/v1/especies/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Listar todas as espécies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarEspecies: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/especies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EspeciesApi - functional programming interface
 */
export const EspeciesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EspeciesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Atualizar dados da espécie
         * @param {string} id 
         * @param {EspecieRequest} [especieRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async atualizarEspecie(id: string, especieRequest?: EspecieRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseEspecie>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.atualizarEspecie(id, especieRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EspeciesApi.atualizarEspecie']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Buscar espécie por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async buscarEspeciePorId(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseEspecie>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.buscarEspeciePorId(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EspeciesApi.buscarEspeciePorId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Cadastrar nova espécie
         * @param {EspecieRequest} [especieRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async criarEspecie(especieRequest?: EspecieRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseEspecie>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.criarEspecie(especieRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EspeciesApi.criarEspecie']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Remover espécie
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletarEspecie(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletarEspecie(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EspeciesApi.deletarEspecie']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Listar todas as espécies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listarEspecies(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListaEspecie>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listarEspecies(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EspeciesApi.listarEspecies']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EspeciesApi - factory interface
 */
export const EspeciesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EspeciesApiFp(configuration)
    return {
        /**
         * 
         * @summary Atualizar dados da espécie
         * @param {string} id 
         * @param {EspecieRequest} [especieRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarEspecie(id: string, especieRequest?: EspecieRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseEspecie> {
            return localVarFp.atualizarEspecie(id, especieRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Buscar espécie por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarEspeciePorId(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseEspecie> {
            return localVarFp.buscarEspeciePorId(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Cadastrar nova espécie
         * @param {EspecieRequest} [especieRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarEspecie(especieRequest?: EspecieRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseEspecie> {
            return localVarFp.criarEspecie(especieRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Remover espécie
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarEspecie(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deletarEspecie(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Listar todas as espécies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarEspecies(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListaEspecie> {
            return localVarFp.listarEspecies(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EspeciesApi - object-oriented interface
 */
export class EspeciesApi extends BaseAPI {
    /**
     * 
     * @summary Atualizar dados da espécie
     * @param {string} id 
     * @param {EspecieRequest} [especieRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public atualizarEspecie(id: string, especieRequest?: EspecieRequest, options?: RawAxiosRequestConfig) {
        return EspeciesApiFp(this.configuration).atualizarEspecie(id, especieRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Buscar espécie por ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public buscarEspeciePorId(id: string, options?: RawAxiosRequestConfig) {
        return EspeciesApiFp(this.configuration).buscarEspeciePorId(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Cadastrar nova espécie
     * @param {EspecieRequest} [especieRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public criarEspecie(especieRequest?: EspecieRequest, options?: RawAxiosRequestConfig) {
        return EspeciesApiFp(this.configuration).criarEspecie(especieRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Remover espécie
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletarEspecie(id: string, options?: RawAxiosRequestConfig) {
        return EspeciesApiFp(this.configuration).deletarEspecie(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Listar todas as espécies
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listarEspecies(options?: RawAxiosRequestConfig) {
        return EspeciesApiFp(this.configuration).listarEspecies(options).then((request) => request(this.axios, this.basePath));
    }
}

