/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseListaModeloExame } from '../models';
// @ts-ignore
import type { ApiResponseModeloExame } from '../models';
// @ts-ignore
import type { ModeloExameRequest } from '../models';
/**
 * ExamesFisicosApi - axios parameter creator
 */
export const ExamesFisicosApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Atualizar modelo de exame físico
         * @param {string} especieId 
         * @param {ModeloExameRequest} [modeloExameRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarModeloExame: async (especieId: string, modeloExameRequest?: ModeloExameRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'especieId' is not null or undefined
            assertParamExists('atualizarModeloExame', 'especieId', especieId)
            const localVarPath = `/api/v1/especies/{especieId}/exame-fisico`
                .replace(`{${"especieId"}}`, encodeURIComponent(String(especieId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(modeloExameRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Define o template padrão para uma espécie específica.
         * @summary Criar modelo de exame físico
         * @param {string} especieId 
         * @param {ModeloExameRequest} [modeloExameRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarModeloExame: async (especieId: string, modeloExameRequest?: ModeloExameRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'especieId' is not null or undefined
            assertParamExists('criarModeloExame', 'especieId', especieId)
            const localVarPath = `/api/v1/especies/{especieId}/exame-fisico`
                .replace(`{${"especieId"}}`, encodeURIComponent(String(especieId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(modeloExameRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Remover modelo de exame físico
         * @param {string} especieId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarModeloExame: async (especieId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'especieId' is not null or undefined
            assertParamExists('deletarModeloExame', 'especieId', especieId)
            const localVarPath = `/api/v1/especies/{especieId}/exame-fisico`
                .replace(`{${"especieId"}}`, encodeURIComponent(String(especieId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retorna todos os templates de exame físico de todas as espécies.
         * @summary Listar todos os modelos cadastrados
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarTodosModelosExame: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/exames-fisicos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Obter modelo de exame físico da espécie
         * @param {string} especieId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        obterModeloExame: async (especieId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'especieId' is not null or undefined
            assertParamExists('obterModeloExame', 'especieId', especieId)
            const localVarPath = `/api/v1/especies/{especieId}/exame-fisico`
                .replace(`{${"especieId"}}`, encodeURIComponent(String(especieId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExamesFisicosApi - functional programming interface
 */
export const ExamesFisicosApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExamesFisicosApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Atualizar modelo de exame físico
         * @param {string} especieId 
         * @param {ModeloExameRequest} [modeloExameRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async atualizarModeloExame(especieId: string, modeloExameRequest?: ModeloExameRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseModeloExame>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.atualizarModeloExame(especieId, modeloExameRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExamesFisicosApi.atualizarModeloExame']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Define o template padrão para uma espécie específica.
         * @summary Criar modelo de exame físico
         * @param {string} especieId 
         * @param {ModeloExameRequest} [modeloExameRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async criarModeloExame(especieId: string, modeloExameRequest?: ModeloExameRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseModeloExame>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.criarModeloExame(especieId, modeloExameRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExamesFisicosApi.criarModeloExame']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Remover modelo de exame físico
         * @param {string} especieId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletarModeloExame(especieId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletarModeloExame(especieId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExamesFisicosApi.deletarModeloExame']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retorna todos os templates de exame físico de todas as espécies.
         * @summary Listar todos os modelos cadastrados
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listarTodosModelosExame(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListaModeloExame>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listarTodosModelosExame(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExamesFisicosApi.listarTodosModelosExame']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Obter modelo de exame físico da espécie
         * @param {string} especieId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async obterModeloExame(especieId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseModeloExame>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.obterModeloExame(especieId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExamesFisicosApi.obterModeloExame']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ExamesFisicosApi - factory interface
 */
export const ExamesFisicosApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExamesFisicosApiFp(configuration)
    return {
        /**
         * 
         * @summary Atualizar modelo de exame físico
         * @param {string} especieId 
         * @param {ModeloExameRequest} [modeloExameRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarModeloExame(especieId: string, modeloExameRequest?: ModeloExameRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseModeloExame> {
            return localVarFp.atualizarModeloExame(especieId, modeloExameRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Define o template padrão para uma espécie específica.
         * @summary Criar modelo de exame físico
         * @param {string} especieId 
         * @param {ModeloExameRequest} [modeloExameRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarModeloExame(especieId: string, modeloExameRequest?: ModeloExameRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseModeloExame> {
            return localVarFp.criarModeloExame(especieId, modeloExameRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Remover modelo de exame físico
         * @param {string} especieId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarModeloExame(especieId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deletarModeloExame(especieId, options).then((request) => request(axios, basePath));
        },
        /**
         * Retorna todos os templates de exame físico de todas as espécies.
         * @summary Listar todos os modelos cadastrados
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarTodosModelosExame(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListaModeloExame> {
            return localVarFp.listarTodosModelosExame(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Obter modelo de exame físico da espécie
         * @param {string} especieId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        obterModeloExame(especieId: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseModeloExame> {
            return localVarFp.obterModeloExame(especieId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ExamesFisicosApi - object-oriented interface
 */
export class ExamesFisicosApi extends BaseAPI {
    /**
     * 
     * @summary Atualizar modelo de exame físico
     * @param {string} especieId 
     * @param {ModeloExameRequest} [modeloExameRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public atualizarModeloExame(especieId: string, modeloExameRequest?: ModeloExameRequest, options?: RawAxiosRequestConfig) {
        return ExamesFisicosApiFp(this.configuration).atualizarModeloExame(especieId, modeloExameRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Define o template padrão para uma espécie específica.
     * @summary Criar modelo de exame físico
     * @param {string} especieId 
     * @param {ModeloExameRequest} [modeloExameRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public criarModeloExame(especieId: string, modeloExameRequest?: ModeloExameRequest, options?: RawAxiosRequestConfig) {
        return ExamesFisicosApiFp(this.configuration).criarModeloExame(especieId, modeloExameRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Remover modelo de exame físico
     * @param {string} especieId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletarModeloExame(especieId: string, options?: RawAxiosRequestConfig) {
        return ExamesFisicosApiFp(this.configuration).deletarModeloExame(especieId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retorna todos os templates de exame físico de todas as espécies.
     * @summary Listar todos os modelos cadastrados
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listarTodosModelosExame(options?: RawAxiosRequestConfig) {
        return ExamesFisicosApiFp(this.configuration).listarTodosModelosExame(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Obter modelo de exame físico da espécie
     * @param {string} especieId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public obterModeloExame(especieId: string, options?: RawAxiosRequestConfig) {
        return ExamesFisicosApiFp(this.configuration).obterModeloExame(especieId, options).then((request) => request(this.axios, this.basePath));
    }
}

