/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseExameAnexo } from '../models';
// @ts-ignore
import type { ApiResponseListaExameAnexo } from '../models';
/**
 * ExamesApi - axios parameter creator
 */
export const ExamesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Remover anexo
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarExame: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletarExame', 'id', id)
            const localVarPath = `/api/v1/exames/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Listar exames de um atendimento
         * @param {string} atendimentoId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarExamesPorAtendimento: async (atendimentoId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'atendimentoId' is not null or undefined
            assertParamExists('listarExamesPorAtendimento', 'atendimentoId', atendimentoId)
            const localVarPath = `/api/v1/atendimentos/{atendimentoId}/exames`
                .replace(`{${"atendimentoId"}}`, encodeURIComponent(String(atendimentoId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Anexar novo exame/arquivo
         * @param {string} atendimentoId 
         * @param {File} arquivo Arquivo PDF, JPG ou PNG
         * @param {string} [observacoes] Notas sobre o exame (opcional)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadExame: async (atendimentoId: string, arquivo: File, observacoes?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'atendimentoId' is not null or undefined
            assertParamExists('uploadExame', 'atendimentoId', atendimentoId)
            // verify required parameter 'arquivo' is not null or undefined
            assertParamExists('uploadExame', 'arquivo', arquivo)
            const localVarPath = `/api/v1/atendimentos/{atendimentoId}/exames`
                .replace(`{${"atendimentoId"}}`, encodeURIComponent(String(atendimentoId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            if (observacoes !== undefined) {
                localVarQueryParameter['observacoes'] = observacoes;
            }


            if (arquivo !== undefined) { 
                localVarFormParams.append('arquivo', arquivo as any);
            }
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExamesApi - functional programming interface
 */
export const ExamesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExamesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Remover anexo
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletarExame(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletarExame(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExamesApi.deletarExame']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Listar exames de um atendimento
         * @param {string} atendimentoId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listarExamesPorAtendimento(atendimentoId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListaExameAnexo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listarExamesPorAtendimento(atendimentoId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExamesApi.listarExamesPorAtendimento']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Anexar novo exame/arquivo
         * @param {string} atendimentoId 
         * @param {File} arquivo Arquivo PDF, JPG ou PNG
         * @param {string} [observacoes] Notas sobre o exame (opcional)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadExame(atendimentoId: string, arquivo: File, observacoes?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseExameAnexo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadExame(atendimentoId, arquivo, observacoes, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExamesApi.uploadExame']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ExamesApi - factory interface
 */
export const ExamesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExamesApiFp(configuration)
    return {
        /**
         * 
         * @summary Remover anexo
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarExame(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deletarExame(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Listar exames de um atendimento
         * @param {string} atendimentoId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarExamesPorAtendimento(atendimentoId: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListaExameAnexo> {
            return localVarFp.listarExamesPorAtendimento(atendimentoId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Anexar novo exame/arquivo
         * @param {string} atendimentoId 
         * @param {File} arquivo Arquivo PDF, JPG ou PNG
         * @param {string} [observacoes] Notas sobre o exame (opcional)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadExame(atendimentoId: string, arquivo: File, observacoes?: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseExameAnexo> {
            return localVarFp.uploadExame(atendimentoId, arquivo, observacoes, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ExamesApi - object-oriented interface
 */
export class ExamesApi extends BaseAPI {
    /**
     * 
     * @summary Remover anexo
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletarExame(id: string, options?: RawAxiosRequestConfig) {
        return ExamesApiFp(this.configuration).deletarExame(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Listar exames de um atendimento
     * @param {string} atendimentoId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listarExamesPorAtendimento(atendimentoId: string, options?: RawAxiosRequestConfig) {
        return ExamesApiFp(this.configuration).listarExamesPorAtendimento(atendimentoId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Anexar novo exame/arquivo
     * @param {string} atendimentoId 
     * @param {File} arquivo Arquivo PDF, JPG ou PNG
     * @param {string} [observacoes] Notas sobre o exame (opcional)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public uploadExame(atendimentoId: string, arquivo: File, observacoes?: string, options?: RawAxiosRequestConfig) {
        return ExamesApiFp(this.configuration).uploadExame(atendimentoId, arquivo, observacoes, options).then((request) => request(this.axios, this.basePath));
    }
}

