/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseListaUsuario } from '../models';
// @ts-ignore
import type { ApiResponseUsuario } from '../models';
// @ts-ignore
import type { AtualizacaoUsuarioRequest } from '../models';
/**
 * GestaoUsuariosApi - axios parameter creator
 */
export const GestaoUsuariosApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Atualiza nome e CRMV. Não atualiza senha/email por aqui.
         * @summary Atualizar dados cadastrais
         * @param {string} id 
         * @param {AtualizacaoUsuarioRequest} [atualizacaoUsuarioRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarUsuario: async (id: string, atualizacaoUsuarioRequest?: AtualizacaoUsuarioRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('atualizarUsuario', 'id', id)
            const localVarPath = `/api/v1/usuarios/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(atualizacaoUsuarioRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Buscar usuário por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarUsuarioPorId: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('buscarUsuarioPorId', 'id', id)
            const localVarPath = `/api/v1/usuarios/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Remover usuário
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarUsuario: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletarUsuario', 'id', id)
            const localVarPath = `/api/v1/usuarios/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Listar usuários com filtros
         * @param {string} [perfil] Filtrar por perfil
         * @param {boolean} [apenasComCrmv] Se true, traz apenas quem tem CRMV preenchido
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarUsuarios: async (perfil?: string, apenasComCrmv?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/usuarios`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (perfil !== undefined) {
                localVarQueryParameter['perfil'] = perfil;
            }

            if (apenasComCrmv !== undefined) {
                localVarQueryParameter['apenasComCrmv'] = apenasComCrmv;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GestaoUsuariosApi - functional programming interface
 */
export const GestaoUsuariosApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GestaoUsuariosApiAxiosParamCreator(configuration)
    return {
        /**
         * Atualiza nome e CRMV. Não atualiza senha/email por aqui.
         * @summary Atualizar dados cadastrais
         * @param {string} id 
         * @param {AtualizacaoUsuarioRequest} [atualizacaoUsuarioRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async atualizarUsuario(id: string, atualizacaoUsuarioRequest?: AtualizacaoUsuarioRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseUsuario>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.atualizarUsuario(id, atualizacaoUsuarioRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GestaoUsuariosApi.atualizarUsuario']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Buscar usuário por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async buscarUsuarioPorId(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseUsuario>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.buscarUsuarioPorId(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GestaoUsuariosApi.buscarUsuarioPorId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Remover usuário
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletarUsuario(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletarUsuario(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GestaoUsuariosApi.deletarUsuario']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Listar usuários com filtros
         * @param {string} [perfil] Filtrar por perfil
         * @param {boolean} [apenasComCrmv] Se true, traz apenas quem tem CRMV preenchido
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listarUsuarios(perfil?: string, apenasComCrmv?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListaUsuario>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listarUsuarios(perfil, apenasComCrmv, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GestaoUsuariosApi.listarUsuarios']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GestaoUsuariosApi - factory interface
 */
export const GestaoUsuariosApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GestaoUsuariosApiFp(configuration)
    return {
        /**
         * Atualiza nome e CRMV. Não atualiza senha/email por aqui.
         * @summary Atualizar dados cadastrais
         * @param {string} id 
         * @param {AtualizacaoUsuarioRequest} [atualizacaoUsuarioRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarUsuario(id: string, atualizacaoUsuarioRequest?: AtualizacaoUsuarioRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseUsuario> {
            return localVarFp.atualizarUsuario(id, atualizacaoUsuarioRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Buscar usuário por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarUsuarioPorId(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseUsuario> {
            return localVarFp.buscarUsuarioPorId(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Remover usuário
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarUsuario(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deletarUsuario(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Listar usuários com filtros
         * @param {string} [perfil] Filtrar por perfil
         * @param {boolean} [apenasComCrmv] Se true, traz apenas quem tem CRMV preenchido
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarUsuarios(perfil?: string, apenasComCrmv?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListaUsuario> {
            return localVarFp.listarUsuarios(perfil, apenasComCrmv, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GestaoUsuariosApi - object-oriented interface
 */
export class GestaoUsuariosApi extends BaseAPI {
    /**
     * Atualiza nome e CRMV. Não atualiza senha/email por aqui.
     * @summary Atualizar dados cadastrais
     * @param {string} id 
     * @param {AtualizacaoUsuarioRequest} [atualizacaoUsuarioRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public atualizarUsuario(id: string, atualizacaoUsuarioRequest?: AtualizacaoUsuarioRequest, options?: RawAxiosRequestConfig) {
        return GestaoUsuariosApiFp(this.configuration).atualizarUsuario(id, atualizacaoUsuarioRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Buscar usuário por ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public buscarUsuarioPorId(id: string, options?: RawAxiosRequestConfig) {
        return GestaoUsuariosApiFp(this.configuration).buscarUsuarioPorId(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Remover usuário
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletarUsuario(id: string, options?: RawAxiosRequestConfig) {
        return GestaoUsuariosApiFp(this.configuration).deletarUsuario(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Listar usuários com filtros
     * @param {string} [perfil] Filtrar por perfil
     * @param {boolean} [apenasComCrmv] Se true, traz apenas quem tem CRMV preenchido
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listarUsuarios(perfil?: string, apenasComCrmv?: boolean, options?: RawAxiosRequestConfig) {
        return GestaoUsuariosApiFp(this.configuration).listarUsuarios(perfil, apenasComCrmv, options).then((request) => request(this.axios, this.basePath));
    }
}

