/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseListaAplicacaoVacina } from '../models';
/**
 * HubVacinacaoApi - axios parameter creator
 */
export const HubVacinacaoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Listar vacinas atrasadas
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarVacinasAtrasadas: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/hub-vacinacao/atrasadas`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Listar próximas vacinas (30 dias)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarVacinasPrevistas: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/hub-vacinacao/previstas`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HubVacinacaoApi - functional programming interface
 */
export const HubVacinacaoApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HubVacinacaoApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Listar vacinas atrasadas
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listarVacinasAtrasadas(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListaAplicacaoVacina>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listarVacinasAtrasadas(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HubVacinacaoApi.listarVacinasAtrasadas']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Listar próximas vacinas (30 dias)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listarVacinasPrevistas(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListaAplicacaoVacina>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listarVacinasPrevistas(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HubVacinacaoApi.listarVacinasPrevistas']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HubVacinacaoApi - factory interface
 */
export const HubVacinacaoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HubVacinacaoApiFp(configuration)
    return {
        /**
         * 
         * @summary Listar vacinas atrasadas
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarVacinasAtrasadas(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListaAplicacaoVacina> {
            return localVarFp.listarVacinasAtrasadas(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Listar próximas vacinas (30 dias)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarVacinasPrevistas(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListaAplicacaoVacina> {
            return localVarFp.listarVacinasPrevistas(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HubVacinacaoApi - object-oriented interface
 */
export class HubVacinacaoApi extends BaseAPI {
    /**
     * 
     * @summary Listar vacinas atrasadas
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listarVacinasAtrasadas(options?: RawAxiosRequestConfig) {
        return HubVacinacaoApiFp(this.configuration).listarVacinasAtrasadas(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Listar próximas vacinas (30 dias)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listarVacinasPrevistas(options?: RawAxiosRequestConfig) {
        return HubVacinacaoApiFp(this.configuration).listarVacinasPrevistas(options).then((request) => request(this.axios, this.basePath));
    }
}

