/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseListaPaciente } from '../models';
// @ts-ignore
import type { ApiResponsePaciente } from '../models';
// @ts-ignore
import type { PacienteRequest } from '../models';
/**
 * PacientesApi - axios parameter creator
 */
export const PacientesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Atualizar dados do paciente
         * @param {string} id 
         * @param {PacienteRequest} [pacienteRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarPaciente: async (id: string, pacienteRequest?: PacienteRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('atualizarPaciente', 'id', id)
            const localVarPath = `/api/v1/pacientes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pacienteRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Buscar paciente por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarPacientePorId: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('buscarPacientePorId', 'id', id)
            const localVarPath = `/api/v1/pacientes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Cadastrar novo paciente
         * @param {PacienteRequest} [pacienteRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarPaciente: async (pacienteRequest?: PacienteRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/pacientes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pacienteRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove o paciente apenas se não houver atendimentos vinculados
         * @summary Remover paciente
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarPaciente: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletarPaciente', 'id', id)
            const localVarPath = `/api/v1/pacientes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Filtra pelo veterinário logado (ou ID passado)
         * @summary Listar meus pacientes
         * @param {string} veterinarioId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarPacientes: async (veterinarioId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'veterinarioId' is not null or undefined
            assertParamExists('listarPacientes', 'veterinarioId', veterinarioId)
            const localVarPath = `/api/v1/pacientes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (veterinarioId !== undefined) {
                localVarQueryParameter['veterinarioId'] = veterinarioId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PacientesApi - functional programming interface
 */
export const PacientesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PacientesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Atualizar dados do paciente
         * @param {string} id 
         * @param {PacienteRequest} [pacienteRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async atualizarPaciente(id: string, pacienteRequest?: PacienteRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePaciente>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.atualizarPaciente(id, pacienteRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PacientesApi.atualizarPaciente']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Buscar paciente por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async buscarPacientePorId(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePaciente>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.buscarPacientePorId(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PacientesApi.buscarPacientePorId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Cadastrar novo paciente
         * @param {PacienteRequest} [pacienteRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async criarPaciente(pacienteRequest?: PacienteRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePaciente>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.criarPaciente(pacienteRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PacientesApi.criarPaciente']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Remove o paciente apenas se não houver atendimentos vinculados
         * @summary Remover paciente
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletarPaciente(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletarPaciente(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PacientesApi.deletarPaciente']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Filtra pelo veterinário logado (ou ID passado)
         * @summary Listar meus pacientes
         * @param {string} veterinarioId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listarPacientes(veterinarioId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListaPaciente>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listarPacientes(veterinarioId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PacientesApi.listarPacientes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PacientesApi - factory interface
 */
export const PacientesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PacientesApiFp(configuration)
    return {
        /**
         * 
         * @summary Atualizar dados do paciente
         * @param {string} id 
         * @param {PacienteRequest} [pacienteRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarPaciente(id: string, pacienteRequest?: PacienteRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePaciente> {
            return localVarFp.atualizarPaciente(id, pacienteRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Buscar paciente por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarPacientePorId(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePaciente> {
            return localVarFp.buscarPacientePorId(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Cadastrar novo paciente
         * @param {PacienteRequest} [pacienteRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarPaciente(pacienteRequest?: PacienteRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePaciente> {
            return localVarFp.criarPaciente(pacienteRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Remove o paciente apenas se não houver atendimentos vinculados
         * @summary Remover paciente
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarPaciente(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deletarPaciente(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Filtra pelo veterinário logado (ou ID passado)
         * @summary Listar meus pacientes
         * @param {string} veterinarioId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarPacientes(veterinarioId: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListaPaciente> {
            return localVarFp.listarPacientes(veterinarioId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PacientesApi - object-oriented interface
 */
export class PacientesApi extends BaseAPI {
    /**
     * 
     * @summary Atualizar dados do paciente
     * @param {string} id 
     * @param {PacienteRequest} [pacienteRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public atualizarPaciente(id: string, pacienteRequest?: PacienteRequest, options?: RawAxiosRequestConfig) {
        return PacientesApiFp(this.configuration).atualizarPaciente(id, pacienteRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Buscar paciente por ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public buscarPacientePorId(id: string, options?: RawAxiosRequestConfig) {
        return PacientesApiFp(this.configuration).buscarPacientePorId(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Cadastrar novo paciente
     * @param {PacienteRequest} [pacienteRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public criarPaciente(pacienteRequest?: PacienteRequest, options?: RawAxiosRequestConfig) {
        return PacientesApiFp(this.configuration).criarPaciente(pacienteRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Remove o paciente apenas se não houver atendimentos vinculados
     * @summary Remover paciente
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletarPaciente(id: string, options?: RawAxiosRequestConfig) {
        return PacientesApiFp(this.configuration).deletarPaciente(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Filtra pelo veterinário logado (ou ID passado)
     * @summary Listar meus pacientes
     * @param {string} veterinarioId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listarPacientes(veterinarioId: string, options?: RawAxiosRequestConfig) {
        return PacientesApiFp(this.configuration).listarPacientes(veterinarioId, options).then((request) => request(this.axios, this.basePath));
    }
}

