/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseListaPlano } from '../models';
// @ts-ignore
import type { ApiResponsePlano } from '../models';
// @ts-ignore
import type { PlanoRequest } from '../models';
/**
 * PlanosApi - axios parameter creator
 */
export const PlanosApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Buscar plano por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarPlanoPorId: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('buscarPlanoPorId', 'id', id)
            const localVarPath = `/api/v1/saas/planos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Criar novo plano (Super Admin)
         * @param {PlanoRequest} [planoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarPlano: async (planoRequest?: PlanoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/saas/planos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(planoRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Listar planos disponíveis
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarPlanos: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/saas/planos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PlanosApi - functional programming interface
 */
export const PlanosApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PlanosApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Buscar plano por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async buscarPlanoPorId(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePlano>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.buscarPlanoPorId(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PlanosApi.buscarPlanoPorId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Criar novo plano (Super Admin)
         * @param {PlanoRequest} [planoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async criarPlano(planoRequest?: PlanoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePlano>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.criarPlano(planoRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PlanosApi.criarPlano']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Listar planos disponíveis
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listarPlanos(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListaPlano>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listarPlanos(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PlanosApi.listarPlanos']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PlanosApi - factory interface
 */
export const PlanosApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PlanosApiFp(configuration)
    return {
        /**
         * 
         * @summary Buscar plano por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarPlanoPorId(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePlano> {
            return localVarFp.buscarPlanoPorId(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Criar novo plano (Super Admin)
         * @param {PlanoRequest} [planoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarPlano(planoRequest?: PlanoRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePlano> {
            return localVarFp.criarPlano(planoRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Listar planos disponíveis
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarPlanos(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListaPlano> {
            return localVarFp.listarPlanos(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PlanosApi - object-oriented interface
 */
export class PlanosApi extends BaseAPI {
    /**
     * 
     * @summary Buscar plano por ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public buscarPlanoPorId(id: string, options?: RawAxiosRequestConfig) {
        return PlanosApiFp(this.configuration).buscarPlanoPorId(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Criar novo plano (Super Admin)
     * @param {PlanoRequest} [planoRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public criarPlano(planoRequest?: PlanoRequest, options?: RawAxiosRequestConfig) {
        return PlanosApiFp(this.configuration).criarPlano(planoRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Listar planos disponíveis
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listarPlanos(options?: RawAxiosRequestConfig) {
        return PlanosApiFp(this.configuration).listarPlanos(options).then((request) => request(this.axios, this.basePath));
    }
}

