/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseListaPrincipioAtivo } from '../models';
// @ts-ignore
import type { ApiResponsePrincipioAtivo } from '../models';
// @ts-ignore
import type { PrincipioAtivoRequest } from '../models';
/**
 * PrincipiosAtivosApi - axios parameter creator
 */
export const PrincipiosAtivosApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Atualizar
         * @param {string} id 
         * @param {PrincipioAtivoRequest} [principioAtivoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarPrincipioAtivo: async (id: string, principioAtivoRequest?: PrincipioAtivoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('atualizarPrincipioAtivo', 'id', id)
            const localVarPath = `/api/v1/principios-ativos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(principioAtivoRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Buscar por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarPrincipioAtivoPorId: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('buscarPrincipioAtivoPorId', 'id', id)
            const localVarPath = `/api/v1/principios-ativos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Cadastrar princípio ativo
         * @param {PrincipioAtivoRequest} [principioAtivoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarPrincipioAtivo: async (principioAtivoRequest?: PrincipioAtivoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/principios-ativos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(principioAtivoRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Não permite se houver medicamentos vinculados
         * @summary Remover
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarPrincipioAtivo: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletarPrincipioAtivo', 'id', id)
            const localVarPath = `/api/v1/principios-ativos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Listar todos
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarPrincipiosAtivos: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/principios-ativos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PrincipiosAtivosApi - functional programming interface
 */
export const PrincipiosAtivosApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PrincipiosAtivosApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Atualizar
         * @param {string} id 
         * @param {PrincipioAtivoRequest} [principioAtivoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async atualizarPrincipioAtivo(id: string, principioAtivoRequest?: PrincipioAtivoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePrincipioAtivo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.atualizarPrincipioAtivo(id, principioAtivoRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PrincipiosAtivosApi.atualizarPrincipioAtivo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Buscar por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async buscarPrincipioAtivoPorId(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePrincipioAtivo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.buscarPrincipioAtivoPorId(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PrincipiosAtivosApi.buscarPrincipioAtivoPorId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Cadastrar princípio ativo
         * @param {PrincipioAtivoRequest} [principioAtivoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async criarPrincipioAtivo(principioAtivoRequest?: PrincipioAtivoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePrincipioAtivo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.criarPrincipioAtivo(principioAtivoRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PrincipiosAtivosApi.criarPrincipioAtivo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Não permite se houver medicamentos vinculados
         * @summary Remover
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletarPrincipioAtivo(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletarPrincipioAtivo(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PrincipiosAtivosApi.deletarPrincipioAtivo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Listar todos
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listarPrincipiosAtivos(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListaPrincipioAtivo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listarPrincipiosAtivos(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PrincipiosAtivosApi.listarPrincipiosAtivos']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PrincipiosAtivosApi - factory interface
 */
export const PrincipiosAtivosApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PrincipiosAtivosApiFp(configuration)
    return {
        /**
         * 
         * @summary Atualizar
         * @param {string} id 
         * @param {PrincipioAtivoRequest} [principioAtivoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarPrincipioAtivo(id: string, principioAtivoRequest?: PrincipioAtivoRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePrincipioAtivo> {
            return localVarFp.atualizarPrincipioAtivo(id, principioAtivoRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Buscar por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarPrincipioAtivoPorId(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePrincipioAtivo> {
            return localVarFp.buscarPrincipioAtivoPorId(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Cadastrar princípio ativo
         * @param {PrincipioAtivoRequest} [principioAtivoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarPrincipioAtivo(principioAtivoRequest?: PrincipioAtivoRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePrincipioAtivo> {
            return localVarFp.criarPrincipioAtivo(principioAtivoRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Não permite se houver medicamentos vinculados
         * @summary Remover
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarPrincipioAtivo(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deletarPrincipioAtivo(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Listar todos
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarPrincipiosAtivos(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListaPrincipioAtivo> {
            return localVarFp.listarPrincipiosAtivos(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PrincipiosAtivosApi - object-oriented interface
 */
export class PrincipiosAtivosApi extends BaseAPI {
    /**
     * 
     * @summary Atualizar
     * @param {string} id 
     * @param {PrincipioAtivoRequest} [principioAtivoRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public atualizarPrincipioAtivo(id: string, principioAtivoRequest?: PrincipioAtivoRequest, options?: RawAxiosRequestConfig) {
        return PrincipiosAtivosApiFp(this.configuration).atualizarPrincipioAtivo(id, principioAtivoRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Buscar por ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public buscarPrincipioAtivoPorId(id: string, options?: RawAxiosRequestConfig) {
        return PrincipiosAtivosApiFp(this.configuration).buscarPrincipioAtivoPorId(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Cadastrar princípio ativo
     * @param {PrincipioAtivoRequest} [principioAtivoRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public criarPrincipioAtivo(principioAtivoRequest?: PrincipioAtivoRequest, options?: RawAxiosRequestConfig) {
        return PrincipiosAtivosApiFp(this.configuration).criarPrincipioAtivo(principioAtivoRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Não permite se houver medicamentos vinculados
     * @summary Remover
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletarPrincipioAtivo(id: string, options?: RawAxiosRequestConfig) {
        return PrincipiosAtivosApiFp(this.configuration).deletarPrincipioAtivo(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Listar todos
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listarPrincipiosAtivos(options?: RawAxiosRequestConfig) {
        return PrincipiosAtivosApiFp(this.configuration).listarPrincipiosAtivos(options).then((request) => request(this.axios, this.basePath));
    }
}

