/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseListaProtocoloVacinal } from '../models';
// @ts-ignore
import type { ApiResponseProtocoloVacinal } from '../models';
// @ts-ignore
import type { ProtocoloVacinalRequest } from '../models';
/**
 * ProtocolosVacinaisApi - axios parameter creator
 */
export const ProtocolosVacinaisApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Atualizar protocolo
         * @param {string} id 
         * @param {ProtocoloVacinalRequest} [protocoloVacinalRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarProtocoloVacinal: async (id: string, protocoloVacinalRequest?: ProtocoloVacinalRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('atualizarProtocoloVacinal', 'id', id)
            const localVarPath = `/api/v1/protocolos-vacinais/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(protocoloVacinalRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Buscar protocolo por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarProtocoloVacinalPorId: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('buscarProtocoloVacinalPorId', 'id', id)
            const localVarPath = `/api/v1/protocolos-vacinais/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Criar protocolo
         * @param {ProtocoloVacinalRequest} [protocoloVacinalRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarProtocoloVacinal: async (protocoloVacinalRequest?: ProtocoloVacinalRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/protocolos-vacinais`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(protocoloVacinalRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Remover protocolo
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarProtocoloVacinal: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletarProtocoloVacinal', 'id', id)
            const localVarPath = `/api/v1/protocolos-vacinais/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Listar por espécie
         * @param {string} especieId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarProtocolosPorEspecie: async (especieId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'especieId' is not null or undefined
            assertParamExists('listarProtocolosPorEspecie', 'especieId', especieId)
            const localVarPath = `/api/v1/especies/{especieId}/protocolos-vacinais`
                .replace(`{${"especieId"}}`, encodeURIComponent(String(especieId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProtocolosVacinaisApi - functional programming interface
 */
export const ProtocolosVacinaisApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProtocolosVacinaisApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Atualizar protocolo
         * @param {string} id 
         * @param {ProtocoloVacinalRequest} [protocoloVacinalRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async atualizarProtocoloVacinal(id: string, protocoloVacinalRequest?: ProtocoloVacinalRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseProtocoloVacinal>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.atualizarProtocoloVacinal(id, protocoloVacinalRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProtocolosVacinaisApi.atualizarProtocoloVacinal']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Buscar protocolo por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async buscarProtocoloVacinalPorId(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseProtocoloVacinal>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.buscarProtocoloVacinalPorId(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProtocolosVacinaisApi.buscarProtocoloVacinalPorId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Criar protocolo
         * @param {ProtocoloVacinalRequest} [protocoloVacinalRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async criarProtocoloVacinal(protocoloVacinalRequest?: ProtocoloVacinalRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseProtocoloVacinal>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.criarProtocoloVacinal(protocoloVacinalRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProtocolosVacinaisApi.criarProtocoloVacinal']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Remover protocolo
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletarProtocoloVacinal(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletarProtocoloVacinal(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProtocolosVacinaisApi.deletarProtocoloVacinal']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Listar por espécie
         * @param {string} especieId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listarProtocolosPorEspecie(especieId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListaProtocoloVacinal>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listarProtocolosPorEspecie(especieId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProtocolosVacinaisApi.listarProtocolosPorEspecie']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProtocolosVacinaisApi - factory interface
 */
export const ProtocolosVacinaisApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProtocolosVacinaisApiFp(configuration)
    return {
        /**
         * 
         * @summary Atualizar protocolo
         * @param {string} id 
         * @param {ProtocoloVacinalRequest} [protocoloVacinalRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarProtocoloVacinal(id: string, protocoloVacinalRequest?: ProtocoloVacinalRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseProtocoloVacinal> {
            return localVarFp.atualizarProtocoloVacinal(id, protocoloVacinalRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Buscar protocolo por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarProtocoloVacinalPorId(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseProtocoloVacinal> {
            return localVarFp.buscarProtocoloVacinalPorId(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Criar protocolo
         * @param {ProtocoloVacinalRequest} [protocoloVacinalRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarProtocoloVacinal(protocoloVacinalRequest?: ProtocoloVacinalRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseProtocoloVacinal> {
            return localVarFp.criarProtocoloVacinal(protocoloVacinalRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Remover protocolo
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarProtocoloVacinal(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deletarProtocoloVacinal(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Listar por espécie
         * @param {string} especieId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarProtocolosPorEspecie(especieId: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListaProtocoloVacinal> {
            return localVarFp.listarProtocolosPorEspecie(especieId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProtocolosVacinaisApi - object-oriented interface
 */
export class ProtocolosVacinaisApi extends BaseAPI {
    /**
     * 
     * @summary Atualizar protocolo
     * @param {string} id 
     * @param {ProtocoloVacinalRequest} [protocoloVacinalRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public atualizarProtocoloVacinal(id: string, protocoloVacinalRequest?: ProtocoloVacinalRequest, options?: RawAxiosRequestConfig) {
        return ProtocolosVacinaisApiFp(this.configuration).atualizarProtocoloVacinal(id, protocoloVacinalRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Buscar protocolo por ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public buscarProtocoloVacinalPorId(id: string, options?: RawAxiosRequestConfig) {
        return ProtocolosVacinaisApiFp(this.configuration).buscarProtocoloVacinalPorId(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Criar protocolo
     * @param {ProtocoloVacinalRequest} [protocoloVacinalRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public criarProtocoloVacinal(protocoloVacinalRequest?: ProtocoloVacinalRequest, options?: RawAxiosRequestConfig) {
        return ProtocolosVacinaisApiFp(this.configuration).criarProtocoloVacinal(protocoloVacinalRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Remover protocolo
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletarProtocoloVacinal(id: string, options?: RawAxiosRequestConfig) {
        return ProtocolosVacinaisApiFp(this.configuration).deletarProtocoloVacinal(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Listar por espécie
     * @param {string} especieId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listarProtocolosPorEspecie(especieId: string, options?: RawAxiosRequestConfig) {
        return ProtocolosVacinaisApiFp(this.configuration).listarProtocolosPorEspecie(especieId, options).then((request) => request(this.axios, this.basePath));
    }
}

