/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseListaProtocolo } from '../models';
// @ts-ignore
import type { ApiResponseProtocolo } from '../models';
// @ts-ignore
import type { ApiResponseProtocoloCompleto } from '../models';
// @ts-ignore
import type { ProtocoloRequest } from '../models';
/**
 * ProtocolosApi - axios parameter creator
 */
export const ProtocolosApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Atualizar protocolo
         * @param {string} id 
         * @param {ProtocoloRequest} [protocoloRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarProtocolo: async (id: string, protocoloRequest?: ProtocoloRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('atualizarProtocolo', 'id', id)
            const localVarPath = `/api/v1/protocolos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(protocoloRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Buscar protocolo por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarProtocoloPorId: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('buscarProtocoloPorId', 'id', id)
            const localVarPath = `/api/v1/protocolos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Criar protocolo terapêutico
         * @param {ProtocoloRequest} [protocoloRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarProtocolo: async (protocoloRequest?: ProtocoloRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/protocolos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(protocoloRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Remover protocolo
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarProtocolo: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletarProtocolo', 'id', id)
            const localVarPath = `/api/v1/protocolos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retorna protocolos Oficiais, Institucionais (da clínica) e Próprios (do usuário).
         * @summary Listar protocolos de uma doença
         * @param {string} doencaId 
         * @param {string} [clinicaId] 
         * @param {string} [usuarioId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarProtocolosPorDoenca: async (doencaId: string, clinicaId?: string, usuarioId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'doencaId' is not null or undefined
            assertParamExists('listarProtocolosPorDoenca', 'doencaId', doencaId)
            const localVarPath = `/api/v1/doencas/{doencaId}/protocolos`
                .replace(`{${"doencaId"}}`, encodeURIComponent(String(doencaId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (clinicaId !== undefined) {
                localVarQueryParameter['clinicaId'] = clinicaId;
            }

            if (usuarioId !== undefined) {
                localVarQueryParameter['usuarioId'] = usuarioId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retorna doença, protocolo, dosagens e contraindicações combinadas
         * @summary Obter visão completa do tratamento
         * @param {string} especieId 
         * @param {string} doencaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        obterProtocoloCompleto: async (especieId: string, doencaId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'especieId' is not null or undefined
            assertParamExists('obterProtocoloCompleto', 'especieId', especieId)
            // verify required parameter 'doencaId' is not null or undefined
            assertParamExists('obterProtocoloCompleto', 'doencaId', doencaId)
            const localVarPath = `/api/v1/especies/{especieId}/doencas/{doencaId}/protocolo-completo`
                .replace(`{${"especieId"}}`, encodeURIComponent(String(especieId)))
                .replace(`{${"doencaId"}}`, encodeURIComponent(String(doencaId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProtocolosApi - functional programming interface
 */
export const ProtocolosApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProtocolosApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Atualizar protocolo
         * @param {string} id 
         * @param {ProtocoloRequest} [protocoloRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async atualizarProtocolo(id: string, protocoloRequest?: ProtocoloRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseProtocolo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.atualizarProtocolo(id, protocoloRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProtocolosApi.atualizarProtocolo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Buscar protocolo por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async buscarProtocoloPorId(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseProtocolo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.buscarProtocoloPorId(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProtocolosApi.buscarProtocoloPorId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Criar protocolo terapêutico
         * @param {ProtocoloRequest} [protocoloRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async criarProtocolo(protocoloRequest?: ProtocoloRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseProtocolo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.criarProtocolo(protocoloRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProtocolosApi.criarProtocolo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Remover protocolo
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletarProtocolo(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletarProtocolo(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProtocolosApi.deletarProtocolo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retorna protocolos Oficiais, Institucionais (da clínica) e Próprios (do usuário).
         * @summary Listar protocolos de uma doença
         * @param {string} doencaId 
         * @param {string} [clinicaId] 
         * @param {string} [usuarioId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listarProtocolosPorDoenca(doencaId: string, clinicaId?: string, usuarioId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListaProtocolo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listarProtocolosPorDoenca(doencaId, clinicaId, usuarioId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProtocolosApi.listarProtocolosPorDoenca']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retorna doença, protocolo, dosagens e contraindicações combinadas
         * @summary Obter visão completa do tratamento
         * @param {string} especieId 
         * @param {string} doencaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async obterProtocoloCompleto(especieId: string, doencaId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseProtocoloCompleto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.obterProtocoloCompleto(especieId, doencaId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProtocolosApi.obterProtocoloCompleto']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProtocolosApi - factory interface
 */
export const ProtocolosApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProtocolosApiFp(configuration)
    return {
        /**
         * 
         * @summary Atualizar protocolo
         * @param {string} id 
         * @param {ProtocoloRequest} [protocoloRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarProtocolo(id: string, protocoloRequest?: ProtocoloRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseProtocolo> {
            return localVarFp.atualizarProtocolo(id, protocoloRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Buscar protocolo por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarProtocoloPorId(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseProtocolo> {
            return localVarFp.buscarProtocoloPorId(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Criar protocolo terapêutico
         * @param {ProtocoloRequest} [protocoloRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarProtocolo(protocoloRequest?: ProtocoloRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseProtocolo> {
            return localVarFp.criarProtocolo(protocoloRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Remover protocolo
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarProtocolo(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deletarProtocolo(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retorna protocolos Oficiais, Institucionais (da clínica) e Próprios (do usuário).
         * @summary Listar protocolos de uma doença
         * @param {string} doencaId 
         * @param {string} [clinicaId] 
         * @param {string} [usuarioId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarProtocolosPorDoenca(doencaId: string, clinicaId?: string, usuarioId?: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListaProtocolo> {
            return localVarFp.listarProtocolosPorDoenca(doencaId, clinicaId, usuarioId, options).then((request) => request(axios, basePath));
        },
        /**
         * Retorna doença, protocolo, dosagens e contraindicações combinadas
         * @summary Obter visão completa do tratamento
         * @param {string} especieId 
         * @param {string} doencaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        obterProtocoloCompleto(especieId: string, doencaId: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseProtocoloCompleto> {
            return localVarFp.obterProtocoloCompleto(especieId, doencaId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProtocolosApi - object-oriented interface
 */
export class ProtocolosApi extends BaseAPI {
    /**
     * 
     * @summary Atualizar protocolo
     * @param {string} id 
     * @param {ProtocoloRequest} [protocoloRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public atualizarProtocolo(id: string, protocoloRequest?: ProtocoloRequest, options?: RawAxiosRequestConfig) {
        return ProtocolosApiFp(this.configuration).atualizarProtocolo(id, protocoloRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Buscar protocolo por ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public buscarProtocoloPorId(id: string, options?: RawAxiosRequestConfig) {
        return ProtocolosApiFp(this.configuration).buscarProtocoloPorId(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Criar protocolo terapêutico
     * @param {ProtocoloRequest} [protocoloRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public criarProtocolo(protocoloRequest?: ProtocoloRequest, options?: RawAxiosRequestConfig) {
        return ProtocolosApiFp(this.configuration).criarProtocolo(protocoloRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Remover protocolo
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletarProtocolo(id: string, options?: RawAxiosRequestConfig) {
        return ProtocolosApiFp(this.configuration).deletarProtocolo(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retorna protocolos Oficiais, Institucionais (da clínica) e Próprios (do usuário).
     * @summary Listar protocolos de uma doença
     * @param {string} doencaId 
     * @param {string} [clinicaId] 
     * @param {string} [usuarioId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listarProtocolosPorDoenca(doencaId: string, clinicaId?: string, usuarioId?: string, options?: RawAxiosRequestConfig) {
        return ProtocolosApiFp(this.configuration).listarProtocolosPorDoenca(doencaId, clinicaId, usuarioId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retorna doença, protocolo, dosagens e contraindicações combinadas
     * @summary Obter visão completa do tratamento
     * @param {string} especieId 
     * @param {string} doencaId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public obterProtocoloCompleto(especieId: string, doencaId: string, options?: RawAxiosRequestConfig) {
        return ProtocolosApiFp(this.configuration).obterProtocoloCompleto(especieId, doencaId, options).then((request) => request(this.axios, this.basePath));
    }
}

