/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseToken } from '../models';
// @ts-ignore
import type { CadastroSaasRequest } from '../models';
/**
 * PublicoApi - axios parameter creator
 */
export const PublicoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Criar conta com plano e clínica
         * @param {CadastroSaasRequest} [cadastroSaasRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cadastrarClienteSaas: async (cadastroSaasRequest?: CadastroSaasRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/public/cadastro-saas`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cadastroSaasRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PublicoApi - functional programming interface
 */
export const PublicoApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PublicoApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Criar conta com plano e clínica
         * @param {CadastroSaasRequest} [cadastroSaasRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cadastrarClienteSaas(cadastroSaasRequest?: CadastroSaasRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseToken>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cadastrarClienteSaas(cadastroSaasRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PublicoApi.cadastrarClienteSaas']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PublicoApi - factory interface
 */
export const PublicoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PublicoApiFp(configuration)
    return {
        /**
         * 
         * @summary Criar conta com plano e clínica
         * @param {CadastroSaasRequest} [cadastroSaasRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cadastrarClienteSaas(cadastroSaasRequest?: CadastroSaasRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseToken> {
            return localVarFp.cadastrarClienteSaas(cadastroSaasRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PublicoApi - object-oriented interface
 */
export class PublicoApi extends BaseAPI {
    /**
     * 
     * @summary Criar conta com plano e clínica
     * @param {CadastroSaasRequest} [cadastroSaasRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cadastrarClienteSaas(cadastroSaasRequest?: CadastroSaasRequest, options?: RawAxiosRequestConfig) {
        return PublicoApiFp(this.configuration).cadastrarClienteSaas(cadastroSaasRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

