/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseListaReferencia } from '../models';
// @ts-ignore
import type { ApiResponseReferencia } from '../models';
// @ts-ignore
import type { ReferenciaRequest } from '../models';
/**
 * ReferenciasApi - axios parameter creator
 */
export const ReferenciasApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Atualizar referência
         * @param {string} id 
         * @param {ReferenciaRequest} [referenciaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarReferencia: async (id: string, referenciaRequest?: ReferenciaRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('atualizarReferencia', 'id', id)
            const localVarPath = `/api/v1/referencias/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(referenciaRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Buscar por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarReferenciaPorId: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('buscarReferenciaPorId', 'id', id)
            const localVarPath = `/api/v1/referencias/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Cadastrar referência
         * @param {ReferenciaRequest} [referenciaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarReferencia: async (referenciaRequest?: ReferenciaRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/referencias`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(referenciaRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Bloqueia se estiver em uso (Protocolos, Vacinas, etc)
         * @summary Remover referência
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarReferencia: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletarReferencia', 'id', id)
            const localVarPath = `/api/v1/referencias/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Listar todas
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarReferencias: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/referencias`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReferenciasApi - functional programming interface
 */
export const ReferenciasApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ReferenciasApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Atualizar referência
         * @param {string} id 
         * @param {ReferenciaRequest} [referenciaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async atualizarReferencia(id: string, referenciaRequest?: ReferenciaRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseReferencia>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.atualizarReferencia(id, referenciaRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReferenciasApi.atualizarReferencia']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Buscar por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async buscarReferenciaPorId(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseReferencia>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.buscarReferenciaPorId(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReferenciasApi.buscarReferenciaPorId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Cadastrar referência
         * @param {ReferenciaRequest} [referenciaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async criarReferencia(referenciaRequest?: ReferenciaRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseReferencia>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.criarReferencia(referenciaRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReferenciasApi.criarReferencia']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Bloqueia se estiver em uso (Protocolos, Vacinas, etc)
         * @summary Remover referência
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletarReferencia(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletarReferencia(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReferenciasApi.deletarReferencia']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Listar todas
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listarReferencias(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListaReferencia>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listarReferencias(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReferenciasApi.listarReferencias']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ReferenciasApi - factory interface
 */
export const ReferenciasApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ReferenciasApiFp(configuration)
    return {
        /**
         * 
         * @summary Atualizar referência
         * @param {string} id 
         * @param {ReferenciaRequest} [referenciaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarReferencia(id: string, referenciaRequest?: ReferenciaRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseReferencia> {
            return localVarFp.atualizarReferencia(id, referenciaRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Buscar por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarReferenciaPorId(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseReferencia> {
            return localVarFp.buscarReferenciaPorId(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Cadastrar referência
         * @param {ReferenciaRequest} [referenciaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarReferencia(referenciaRequest?: ReferenciaRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseReferencia> {
            return localVarFp.criarReferencia(referenciaRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Bloqueia se estiver em uso (Protocolos, Vacinas, etc)
         * @summary Remover referência
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarReferencia(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deletarReferencia(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Listar todas
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarReferencias(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListaReferencia> {
            return localVarFp.listarReferencias(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ReferenciasApi - object-oriented interface
 */
export class ReferenciasApi extends BaseAPI {
    /**
     * 
     * @summary Atualizar referência
     * @param {string} id 
     * @param {ReferenciaRequest} [referenciaRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public atualizarReferencia(id: string, referenciaRequest?: ReferenciaRequest, options?: RawAxiosRequestConfig) {
        return ReferenciasApiFp(this.configuration).atualizarReferencia(id, referenciaRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Buscar por ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public buscarReferenciaPorId(id: string, options?: RawAxiosRequestConfig) {
        return ReferenciasApiFp(this.configuration).buscarReferenciaPorId(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Cadastrar referência
     * @param {ReferenciaRequest} [referenciaRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public criarReferencia(referenciaRequest?: ReferenciaRequest, options?: RawAxiosRequestConfig) {
        return ReferenciasApiFp(this.configuration).criarReferencia(referenciaRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Bloqueia se estiver em uso (Protocolos, Vacinas, etc)
     * @summary Remover referência
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletarReferencia(id: string, options?: RawAxiosRequestConfig) {
        return ReferenciasApiFp(this.configuration).deletarReferencia(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Listar todas
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listarReferencias(options?: RawAxiosRequestConfig) {
        return ReferenciasApiFp(this.configuration).listarReferencias(options).then((request) => request(this.axios, this.basePath));
    }
}

