/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AlertaSeguranca } from '../models';
/**
 * SegurancaClinicaApi - axios parameter creator
 */
export const SegurancaClinicaApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Validar medicamento para espécie
         * @param {string} medicamentoId 
         * @param {string} especieId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validarSeguranca: async (medicamentoId: string, especieId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'medicamentoId' is not null or undefined
            assertParamExists('validarSeguranca', 'medicamentoId', medicamentoId)
            // verify required parameter 'especieId' is not null or undefined
            assertParamExists('validarSeguranca', 'especieId', especieId)
            const localVarPath = `/api/v1/seguranca/validar`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (medicamentoId !== undefined) {
                localVarQueryParameter['medicamentoId'] = medicamentoId;
            }

            if (especieId !== undefined) {
                localVarQueryParameter['especieId'] = especieId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SegurancaClinicaApi - functional programming interface
 */
export const SegurancaClinicaApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SegurancaClinicaApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Validar medicamento para espécie
         * @param {string} medicamentoId 
         * @param {string} especieId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validarSeguranca(medicamentoId: string, especieId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AlertaSeguranca>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.validarSeguranca(medicamentoId, especieId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SegurancaClinicaApi.validarSeguranca']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SegurancaClinicaApi - factory interface
 */
export const SegurancaClinicaApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SegurancaClinicaApiFp(configuration)
    return {
        /**
         * 
         * @summary Validar medicamento para espécie
         * @param {string} medicamentoId 
         * @param {string} especieId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validarSeguranca(medicamentoId: string, especieId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<AlertaSeguranca>> {
            return localVarFp.validarSeguranca(medicamentoId, especieId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SegurancaClinicaApi - object-oriented interface
 */
export class SegurancaClinicaApi extends BaseAPI {
    /**
     * 
     * @summary Validar medicamento para espécie
     * @param {string} medicamentoId 
     * @param {string} especieId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public validarSeguranca(medicamentoId: string, especieId: string, options?: RawAxiosRequestConfig) {
        return SegurancaClinicaApiFp(this.configuration).validarSeguranca(medicamentoId, especieId, options).then((request) => request(this.axios, this.basePath));
    }
}

