/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseListaSugestao } from '../models';
// @ts-ignore
import type { ApiResponseSugestao } from '../models';
// @ts-ignore
import type { AtualizarStatusRequest } from '../models';
// @ts-ignore
import type { SugestaoRequest } from '../models';
/**
 * SugestoesApi - axios parameter creator
 */
export const SugestoesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Alterar status da sugestão (Admin)
         * @param {string} id 
         * @param {AtualizarStatusRequest} [atualizarStatusRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarStatusSugestao: async (id: string, atualizarStatusRequest?: AtualizarStatusRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('atualizarStatusSugestao', 'id', id)
            const localVarPath = `/api/v1/sugestoes/{id}/status`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(atualizarStatusRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Permite filtrar por tipo (ESPECIE, DOENCA, etc) e status
         * @summary Listar sugestões recebidas
         * @param {ListarSugestoesTipoEnum} [tipo] 
         * @param {ListarSugestoesStatusEnum} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarSugestoes: async (tipo?: ListarSugestoesTipoEnum, status?: ListarSugestoesStatusEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/sugestoes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (tipo !== undefined) {
                localVarQueryParameter['tipo'] = tipo;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Sugerir novo tipo de cálculo
         * @param {SugestaoRequest} [sugestaoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sugerirCalculo: async (sugestaoRequest?: SugestaoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/sugestoes/calculos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sugestaoRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Sugerir doença
         * @param {SugestaoRequest} [sugestaoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sugerirDoenca: async (sugestaoRequest?: SugestaoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/sugestoes/doencas`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sugestaoRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Sugerir nova espécie
         * @param {SugestaoRequest} [sugestaoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sugerirEspecie: async (sugestaoRequest?: SugestaoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/sugestoes/especies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sugestaoRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Sugerir melhoria em protocolo
         * @param {SugestaoRequest} [sugestaoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sugerirProtocolo: async (sugestaoRequest?: SugestaoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/sugestoes/protocolos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sugestaoRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SugestoesApi - functional programming interface
 */
export const SugestoesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SugestoesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Alterar status da sugestão (Admin)
         * @param {string} id 
         * @param {AtualizarStatusRequest} [atualizarStatusRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async atualizarStatusSugestao(id: string, atualizarStatusRequest?: AtualizarStatusRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseSugestao>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.atualizarStatusSugestao(id, atualizarStatusRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SugestoesApi.atualizarStatusSugestao']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Permite filtrar por tipo (ESPECIE, DOENCA, etc) e status
         * @summary Listar sugestões recebidas
         * @param {ListarSugestoesTipoEnum} [tipo] 
         * @param {ListarSugestoesStatusEnum} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listarSugestoes(tipo?: ListarSugestoesTipoEnum, status?: ListarSugestoesStatusEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListaSugestao>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listarSugestoes(tipo, status, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SugestoesApi.listarSugestoes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Sugerir novo tipo de cálculo
         * @param {SugestaoRequest} [sugestaoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sugerirCalculo(sugestaoRequest?: SugestaoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseSugestao>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sugerirCalculo(sugestaoRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SugestoesApi.sugerirCalculo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Sugerir doença
         * @param {SugestaoRequest} [sugestaoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sugerirDoenca(sugestaoRequest?: SugestaoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseSugestao>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sugerirDoenca(sugestaoRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SugestoesApi.sugerirDoenca']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Sugerir nova espécie
         * @param {SugestaoRequest} [sugestaoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sugerirEspecie(sugestaoRequest?: SugestaoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseSugestao>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sugerirEspecie(sugestaoRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SugestoesApi.sugerirEspecie']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Sugerir melhoria em protocolo
         * @param {SugestaoRequest} [sugestaoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sugerirProtocolo(sugestaoRequest?: SugestaoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseSugestao>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sugerirProtocolo(sugestaoRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SugestoesApi.sugerirProtocolo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SugestoesApi - factory interface
 */
export const SugestoesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SugestoesApiFp(configuration)
    return {
        /**
         * 
         * @summary Alterar status da sugestão (Admin)
         * @param {string} id 
         * @param {AtualizarStatusRequest} [atualizarStatusRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarStatusSugestao(id: string, atualizarStatusRequest?: AtualizarStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseSugestao> {
            return localVarFp.atualizarStatusSugestao(id, atualizarStatusRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Permite filtrar por tipo (ESPECIE, DOENCA, etc) e status
         * @summary Listar sugestões recebidas
         * @param {ListarSugestoesTipoEnum} [tipo] 
         * @param {ListarSugestoesStatusEnum} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarSugestoes(tipo?: ListarSugestoesTipoEnum, status?: ListarSugestoesStatusEnum, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListaSugestao> {
            return localVarFp.listarSugestoes(tipo, status, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Sugerir novo tipo de cálculo
         * @param {SugestaoRequest} [sugestaoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sugerirCalculo(sugestaoRequest?: SugestaoRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseSugestao> {
            return localVarFp.sugerirCalculo(sugestaoRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Sugerir doença
         * @param {SugestaoRequest} [sugestaoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sugerirDoenca(sugestaoRequest?: SugestaoRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseSugestao> {
            return localVarFp.sugerirDoenca(sugestaoRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Sugerir nova espécie
         * @param {SugestaoRequest} [sugestaoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sugerirEspecie(sugestaoRequest?: SugestaoRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseSugestao> {
            return localVarFp.sugerirEspecie(sugestaoRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Sugerir melhoria em protocolo
         * @param {SugestaoRequest} [sugestaoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sugerirProtocolo(sugestaoRequest?: SugestaoRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseSugestao> {
            return localVarFp.sugerirProtocolo(sugestaoRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SugestoesApi - object-oriented interface
 */
export class SugestoesApi extends BaseAPI {
    /**
     * 
     * @summary Alterar status da sugestão (Admin)
     * @param {string} id 
     * @param {AtualizarStatusRequest} [atualizarStatusRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public atualizarStatusSugestao(id: string, atualizarStatusRequest?: AtualizarStatusRequest, options?: RawAxiosRequestConfig) {
        return SugestoesApiFp(this.configuration).atualizarStatusSugestao(id, atualizarStatusRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Permite filtrar por tipo (ESPECIE, DOENCA, etc) e status
     * @summary Listar sugestões recebidas
     * @param {ListarSugestoesTipoEnum} [tipo] 
     * @param {ListarSugestoesStatusEnum} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listarSugestoes(tipo?: ListarSugestoesTipoEnum, status?: ListarSugestoesStatusEnum, options?: RawAxiosRequestConfig) {
        return SugestoesApiFp(this.configuration).listarSugestoes(tipo, status, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Sugerir novo tipo de cálculo
     * @param {SugestaoRequest} [sugestaoRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sugerirCalculo(sugestaoRequest?: SugestaoRequest, options?: RawAxiosRequestConfig) {
        return SugestoesApiFp(this.configuration).sugerirCalculo(sugestaoRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Sugerir doença
     * @param {SugestaoRequest} [sugestaoRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sugerirDoenca(sugestaoRequest?: SugestaoRequest, options?: RawAxiosRequestConfig) {
        return SugestoesApiFp(this.configuration).sugerirDoenca(sugestaoRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Sugerir nova espécie
     * @param {SugestaoRequest} [sugestaoRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sugerirEspecie(sugestaoRequest?: SugestaoRequest, options?: RawAxiosRequestConfig) {
        return SugestoesApiFp(this.configuration).sugerirEspecie(sugestaoRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Sugerir melhoria em protocolo
     * @param {SugestaoRequest} [sugestaoRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sugerirProtocolo(sugestaoRequest?: SugestaoRequest, options?: RawAxiosRequestConfig) {
        return SugestoesApiFp(this.configuration).sugerirProtocolo(sugestaoRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

export const ListarSugestoesTipoEnum = {
    Especie: 'ESPECIE',
    Doenca: 'DOENCA',
    Protocolo: 'PROTOCOLO',
    Calculo: 'CALCULO',
    Outro: 'OUTRO'
} as const;
export type ListarSugestoesTipoEnum = typeof ListarSugestoesTipoEnum[keyof typeof ListarSugestoesTipoEnum];
export const ListarSugestoesStatusEnum = {
    Pendente: 'PENDENTE',
    EmAnalise: 'EM_ANALISE',
    Aprovada: 'APROVADA',
    Rejeitada: 'REJEITADA'
} as const;
export type ListarSugestoesStatusEnum = typeof ListarSugestoesStatusEnum[keyof typeof ListarSugestoesStatusEnum];
