/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseAplicacaoVacina } from '../models';
// @ts-ignore
import type { ApiResponseListaAplicacaoVacina } from '../models';
// @ts-ignore
import type { AplicacaoVacinaRequest } from '../models';
/**
 * VacinacaoPacienteApi - axios parameter creator
 */
export const VacinacaoPacienteApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Remover registro de vacina (se erro)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarVacinaAplicada: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletarVacinaAplicada', 'id', id)
            const localVarPath = `/api/v1/vacinas-aplicadas/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Listar vacinas aplicadas no paciente
         * @param {string} pacienteId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarVacinasDoPaciente: async (pacienteId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pacienteId' is not null or undefined
            assertParamExists('listarVacinasDoPaciente', 'pacienteId', pacienteId)
            const localVarPath = `/api/v1/pacientes/{pacienteId}/vacinas`
                .replace(`{${"pacienteId"}}`, encodeURIComponent(String(pacienteId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Registrar aplicação de vacina
         * @param {string} pacienteId 
         * @param {string} veterinarioId 
         * @param {AplicacaoVacinaRequest} [aplicacaoVacinaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registrarVacinaPaciente: async (pacienteId: string, veterinarioId: string, aplicacaoVacinaRequest?: AplicacaoVacinaRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pacienteId' is not null or undefined
            assertParamExists('registrarVacinaPaciente', 'pacienteId', pacienteId)
            // verify required parameter 'veterinarioId' is not null or undefined
            assertParamExists('registrarVacinaPaciente', 'veterinarioId', veterinarioId)
            const localVarPath = `/api/v1/pacientes/{pacienteId}/vacinas`
                .replace(`{${"pacienteId"}}`, encodeURIComponent(String(pacienteId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (veterinarioId !== undefined) {
                localVarQueryParameter['veterinarioId'] = veterinarioId;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(aplicacaoVacinaRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VacinacaoPacienteApi - functional programming interface
 */
export const VacinacaoPacienteApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VacinacaoPacienteApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Remover registro de vacina (se erro)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletarVacinaAplicada(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletarVacinaAplicada(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VacinacaoPacienteApi.deletarVacinaAplicada']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Listar vacinas aplicadas no paciente
         * @param {string} pacienteId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listarVacinasDoPaciente(pacienteId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListaAplicacaoVacina>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listarVacinasDoPaciente(pacienteId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VacinacaoPacienteApi.listarVacinasDoPaciente']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Registrar aplicação de vacina
         * @param {string} pacienteId 
         * @param {string} veterinarioId 
         * @param {AplicacaoVacinaRequest} [aplicacaoVacinaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registrarVacinaPaciente(pacienteId: string, veterinarioId: string, aplicacaoVacinaRequest?: AplicacaoVacinaRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseAplicacaoVacina>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registrarVacinaPaciente(pacienteId, veterinarioId, aplicacaoVacinaRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VacinacaoPacienteApi.registrarVacinaPaciente']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * VacinacaoPacienteApi - factory interface
 */
export const VacinacaoPacienteApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VacinacaoPacienteApiFp(configuration)
    return {
        /**
         * 
         * @summary Remover registro de vacina (se erro)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarVacinaAplicada(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deletarVacinaAplicada(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Listar vacinas aplicadas no paciente
         * @param {string} pacienteId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarVacinasDoPaciente(pacienteId: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListaAplicacaoVacina> {
            return localVarFp.listarVacinasDoPaciente(pacienteId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Registrar aplicação de vacina
         * @param {string} pacienteId 
         * @param {string} veterinarioId 
         * @param {AplicacaoVacinaRequest} [aplicacaoVacinaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registrarVacinaPaciente(pacienteId: string, veterinarioId: string, aplicacaoVacinaRequest?: AplicacaoVacinaRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseAplicacaoVacina> {
            return localVarFp.registrarVacinaPaciente(pacienteId, veterinarioId, aplicacaoVacinaRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VacinacaoPacienteApi - object-oriented interface
 */
export class VacinacaoPacienteApi extends BaseAPI {
    /**
     * 
     * @summary Remover registro de vacina (se erro)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletarVacinaAplicada(id: string, options?: RawAxiosRequestConfig) {
        return VacinacaoPacienteApiFp(this.configuration).deletarVacinaAplicada(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Listar vacinas aplicadas no paciente
     * @param {string} pacienteId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listarVacinasDoPaciente(pacienteId: string, options?: RawAxiosRequestConfig) {
        return VacinacaoPacienteApiFp(this.configuration).listarVacinasDoPaciente(pacienteId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Registrar aplicação de vacina
     * @param {string} pacienteId 
     * @param {string} veterinarioId 
     * @param {AplicacaoVacinaRequest} [aplicacaoVacinaRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public registrarVacinaPaciente(pacienteId: string, veterinarioId: string, aplicacaoVacinaRequest?: AplicacaoVacinaRequest, options?: RawAxiosRequestConfig) {
        return VacinacaoPacienteApiFp(this.configuration).registrarVacinaPaciente(pacienteId, veterinarioId, aplicacaoVacinaRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

