/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseListaVacina } from '../models';
// @ts-ignore
import type { ApiResponseVacina } from '../models';
// @ts-ignore
import type { VacinaRequest } from '../models';
/**
 * VacinasApi - axios parameter creator
 */
export const VacinasApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Atualizar vacina
         * @param {string} id 
         * @param {VacinaRequest} [vacinaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarVacina: async (id: string, vacinaRequest?: VacinaRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('atualizarVacina', 'id', id)
            const localVarPath = `/api/v1/vacinas/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(vacinaRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Buscar por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarVacinaPorId: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('buscarVacinaPorId', 'id', id)
            const localVarPath = `/api/v1/vacinas/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Cadastrar vacina
         * @param {VacinaRequest} [vacinaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarVacina: async (vacinaRequest?: VacinaRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/vacinas`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(vacinaRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Não permite remover se estiver em uso num protocolo
         * @summary Remover vacina
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarVacina: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletarVacina', 'id', id)
            const localVarPath = `/api/v1/vacinas/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Listar todas
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarVacinas: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/vacinas`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VacinasApi - functional programming interface
 */
export const VacinasApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VacinasApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Atualizar vacina
         * @param {string} id 
         * @param {VacinaRequest} [vacinaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async atualizarVacina(id: string, vacinaRequest?: VacinaRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseVacina>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.atualizarVacina(id, vacinaRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VacinasApi.atualizarVacina']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Buscar por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async buscarVacinaPorId(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseVacina>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.buscarVacinaPorId(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VacinasApi.buscarVacinaPorId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Cadastrar vacina
         * @param {VacinaRequest} [vacinaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async criarVacina(vacinaRequest?: VacinaRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseVacina>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.criarVacina(vacinaRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VacinasApi.criarVacina']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Não permite remover se estiver em uso num protocolo
         * @summary Remover vacina
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletarVacina(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletarVacina(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VacinasApi.deletarVacina']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Listar todas
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listarVacinas(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListaVacina>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listarVacinas(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VacinasApi.listarVacinas']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * VacinasApi - factory interface
 */
export const VacinasApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VacinasApiFp(configuration)
    return {
        /**
         * 
         * @summary Atualizar vacina
         * @param {string} id 
         * @param {VacinaRequest} [vacinaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atualizarVacina(id: string, vacinaRequest?: VacinaRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVacina> {
            return localVarFp.atualizarVacina(id, vacinaRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Buscar por ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buscarVacinaPorId(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVacina> {
            return localVarFp.buscarVacinaPorId(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Cadastrar vacina
         * @param {VacinaRequest} [vacinaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        criarVacina(vacinaRequest?: VacinaRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVacina> {
            return localVarFp.criarVacina(vacinaRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Não permite remover se estiver em uso num protocolo
         * @summary Remover vacina
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletarVacina(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deletarVacina(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Listar todas
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listarVacinas(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListaVacina> {
            return localVarFp.listarVacinas(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VacinasApi - object-oriented interface
 */
export class VacinasApi extends BaseAPI {
    /**
     * 
     * @summary Atualizar vacina
     * @param {string} id 
     * @param {VacinaRequest} [vacinaRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public atualizarVacina(id: string, vacinaRequest?: VacinaRequest, options?: RawAxiosRequestConfig) {
        return VacinasApiFp(this.configuration).atualizarVacina(id, vacinaRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Buscar por ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public buscarVacinaPorId(id: string, options?: RawAxiosRequestConfig) {
        return VacinasApiFp(this.configuration).buscarVacinaPorId(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Cadastrar vacina
     * @param {VacinaRequest} [vacinaRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public criarVacina(vacinaRequest?: VacinaRequest, options?: RawAxiosRequestConfig) {
        return VacinasApiFp(this.configuration).criarVacina(vacinaRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Não permite remover se estiver em uso num protocolo
     * @summary Remover vacina
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletarVacina(id: string, options?: RawAxiosRequestConfig) {
        return VacinasApiFp(this.configuration).deletarVacina(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Listar todas
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listarVacinas(options?: RawAxiosRequestConfig) {
        return VacinasApiFp(this.configuration).listarVacinas(options).then((request) => request(this.axios, this.basePath));
    }
}

