/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { WebhookMP } from '../models';
/**
 * WebhookControllerApi - axios parameter creator
 */
export const WebhookControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {WebhookMP} webhookMP 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        receberNotificacao: async (webhookMP: WebhookMP, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'webhookMP' is not null or undefined
            assertParamExists('receberNotificacao', 'webhookMP', webhookMP)
            const localVarPath = `/api/v1/public/webhooks/mercadopago`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(webhookMP, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WebhookControllerApi - functional programming interface
 */
export const WebhookControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WebhookControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {WebhookMP} webhookMP 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async receberNotificacao(webhookMP: WebhookMP, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.receberNotificacao(webhookMP, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WebhookControllerApi.receberNotificacao']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WebhookControllerApi - factory interface
 */
export const WebhookControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WebhookControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {WebhookMP} webhookMP 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        receberNotificacao(webhookMP: WebhookMP, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.receberNotificacao(webhookMP, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WebhookControllerApi - object-oriented interface
 */
export class WebhookControllerApi extends BaseAPI {
    /**
     * 
     * @param {WebhookMP} webhookMP 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public receberNotificacao(webhookMP: WebhookMP, options?: RawAxiosRequestConfig) {
        return WebhookControllerApiFp(this.configuration).receberNotificacao(webhookMP, options).then((request) => request(this.axios, this.basePath));
    }
}

