/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AlertaSeguranca {
    'nivel'?: AlertaSegurancaNivelEnum;
    'descricao'?: string;
    'medicamento'?: string;
    'principioAtivo'?: string;
}

export const AlertaSegurancaNivelEnum = {
    Leve: 'LEVE',
    Moderada: 'MODERADA',
    Grave: 'GRAVE',
    Fatal: 'FATAL'
} as const;

export type AlertaSegurancaNivelEnum = typeof AlertaSegurancaNivelEnum[keyof typeof AlertaSegurancaNivelEnum];


