/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AplicacaoVacinaResponse {
    'id'?: string;
    'pacienteId'?: string;
    'pacienteNome'?: string;
    'pacienteEspecie'?: string;
    'tutorNome'?: string;
    'vacinaId'?: string;
    'vacinaNome'?: string;
    'dataAplicacao'?: string;
    'dataProximaDose'?: string;
    'status'?: AplicacaoVacinaResponseStatusEnum;
    'lote'?: string;
    'via'?: string;
    'doseAplicada'?: string;
    'observacoes'?: string;
    'veterinarioNome'?: string;
}

export const AplicacaoVacinaResponseStatusEnum = {
    EmDia: 'EM_DIA',
    Atrasada: 'ATRASADA',
    Concluida: 'CONCLUIDA'
} as const;

export type AplicacaoVacinaResponseStatusEnum = typeof AplicacaoVacinaResponseStatusEnum[keyof typeof AplicacaoVacinaResponseStatusEnum];


