/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PlanoResponse } from './plano-response';

export interface AssinaturaResponse {
    'id'?: string;
    'clinicaId'?: string;
    'plano'?: PlanoResponse;
    'status'?: AssinaturaResponseStatusEnum;
    'tipoFaturamento'?: AssinaturaResponseTipoFaturamentoEnum;
    'dataInicio'?: string;
    'dataFim'?: string;
    'dataTrialFim'?: string;
}

export const AssinaturaResponseStatusEnum = {
    Trial: 'TRIAL',
    Ativo: 'ATIVO',
    Bloqueado: 'BLOQUEADO',
    Inadimplente: 'INADIMPLENTE',
    Cancelado: 'CANCELADO'
} as const;

export type AssinaturaResponseStatusEnum = typeof AssinaturaResponseStatusEnum[keyof typeof AssinaturaResponseStatusEnum];
export const AssinaturaResponseTipoFaturamentoEnum = {
    Auto: 'AUTO',
    Manual: 'MANUAL'
} as const;

export type AssinaturaResponseTipoFaturamentoEnum = typeof AssinaturaResponseTipoFaturamentoEnum[keyof typeof AssinaturaResponseTipoFaturamentoEnum];


