/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AtendimentoRequest {
    'pacienteId': string;
    'veterinarioId': string;
    'protocoloId'?: string;
    'dataHora'?: string;
    'titulo': string;
    'status'?: AtendimentoRequestStatusEnum;
    'queixaPrincipal'?: string;
    'historicoClinico'?: string;
    'exameFisico'?: string;
    'diagnostico'?: string;
    'condutaClinica'?: string;
    'observacoes'?: string;
    /**
     * JSON stringificado contendo os 8 pilares de manejo
     */
    'orientacoesManejo'?: string;
}

export const AtendimentoRequestStatusEnum = {
    Agendado: 'AGENDADO',
    EmAndamento: 'EM_ANDAMENTO',
    Realizado: 'REALIZADO',
    Cancelado: 'CANCELADO'
} as const;

export type AtendimentoRequestStatusEnum = typeof AtendimentoRequestStatusEnum[keyof typeof AtendimentoRequestStatusEnum];


