/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AtendimentoResponse {
    'id'?: string;
    'pacienteId'?: string;
    'dataHora'?: string;
    'titulo'?: string;
    'status'?: AtendimentoResponseStatusEnum;
    'queixaPrincipal'?: string;
    'historicoClinico'?: string;
    'exameFisico'?: string;
    'diagnostico'?: string;
    'condutaClinica'?: string;
    'observacoes'?: string;
    'protocoloId'?: string;
    'veterinarioId'?: string;
    'veterinarioNome'?: string;
    'veterinarioCrmv'?: string;
    'pacienteNome'?: string;
    'pacienteEspecie'?: string;
    'orientacoesManejo'?: string;
}

export const AtendimentoResponseStatusEnum = {
    Agendado: 'AGENDADO',
    EmAndamento: 'EM_ANDAMENTO',
    Realizado: 'REALIZADO',
    Cancelado: 'CANCELADO'
} as const;

export type AtendimentoResponseStatusEnum = typeof AtendimentoResponseStatusEnum[keyof typeof AtendimentoResponseStatusEnum];


