/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AtualizarStatusRequest {
    'status': AtualizarStatusRequestStatusEnum;
}

export const AtualizarStatusRequestStatusEnum = {
    Pendente: 'PENDENTE',
    EmAnalise: 'EM_ANALISE',
    Aprovada: 'APROVADA',
    Rejeitada: 'REJEITADA'
} as const;

export type AtualizarStatusRequestStatusEnum = typeof AtualizarStatusRequestStatusEnum[keyof typeof AtualizarStatusRequestStatusEnum];


