/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AtualizarStatusAtendimentoRequest {
    'status'?: AtualizarStatusAtendimentoRequestStatusEnum;
}

export const AtualizarStatusAtendimentoRequestStatusEnum = {
    Agendado: 'AGENDADO',
    EmAndamento: 'EM_ANDAMENTO',
    Realizado: 'REALIZADO',
    Cancelado: 'CANCELADO'
} as const;

export type AtualizarStatusAtendimentoRequestStatusEnum = typeof AtualizarStatusAtendimentoRequestStatusEnum[keyof typeof AtualizarStatusAtendimentoRequestStatusEnum];


