/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CalculoCatalogoRequest {
    'medicamentoId': string;
    'especieId': string;
    'doencaId'?: string;
    'clinicaId'?: string;
    'usuarioId'?: string;
    'peso': number;
    'doseInformada': number;
    'unidadePeso': CalculoCatalogoRequestUnidadePesoEnum;
    'via'?: string;
}

export const CalculoCatalogoRequestUnidadePesoEnum = {
    Kg: 'KG',
    G: 'G'
} as const;

export type CalculoCatalogoRequestUnidadePesoEnum = typeof CalculoCatalogoRequestUnidadePesoEnum[keyof typeof CalculoCatalogoRequestUnidadePesoEnum];


