/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JsonNullableDouble } from './json-nullable-double';
// May contain unused imports in some cases
// @ts-ignore
import type { JsonNullableString } from './json-nullable-string';
// May contain unused imports in some cases
// @ts-ignore
import type { JsonNullableUUID } from './json-nullable-uuid';

export interface CalculoValidacaoRequest {
    'medicamentoId'?: JsonNullableUUID;
    'especieId'?: JsonNullableUUID;
    'peso': number;
    /**
     * A dose que o vet quer usar (mg/kg)
     */
    'doseInformada': number;
    'unidadePeso': CalculoValidacaoRequestUnidadePesoEnum;
    'concentracaoInformada'?: JsonNullableDouble;
    'doencaId'?: JsonNullableUUID;
    'via'?: JsonNullableString;
    'clinicaId'?: JsonNullableUUID;
    'usuarioId'?: JsonNullableUUID;
}

export const CalculoValidacaoRequestUnidadePesoEnum = {
    Kg: 'KG',
    G: 'G'
} as const;

export type CalculoValidacaoRequestUnidadePesoEnum = typeof CalculoValidacaoRequestUnidadePesoEnum[keyof typeof CalculoValidacaoRequestUnidadePesoEnum];


