/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CalculoLivreRequest {
    'peso': number;
    'doseInformada': number;
    'concentracao': number;
    'unidadePeso': CalculoLivreRequestUnidadePesoEnum;
    'nomeMedicamento'?: string;
    'via'?: string;
    'frequencia'?: string;
    'duracao'?: string;
}

export const CalculoLivreRequestUnidadePesoEnum = {
    Kg: 'KG',
    G: 'G'
} as const;

export type CalculoLivreRequestUnidadePesoEnum = typeof CalculoLivreRequestUnidadePesoEnum[keyof typeof CalculoLivreRequestUnidadePesoEnum];


