/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ContraindicacaoResponse {
    'id'?: string;
    'medicamentoId'?: string;
    'especieId'?: string;
    'referenciaId'?: string;
    'gravidade'?: ContraindicacaoResponseGravidadeEnum;
    'descricao'?: string;
}

export const ContraindicacaoResponseGravidadeEnum = {
    Leve: 'LEVE',
    Moderada: 'MODERADA',
    Grave: 'GRAVE',
    Fatal: 'FATAL'
} as const;

export type ContraindicacaoResponseGravidadeEnum = typeof ContraindicacaoResponseGravidadeEnum[keyof typeof ContraindicacaoResponseGravidadeEnum];


