/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JsonNullableUUID } from './json-nullable-uuid';

export interface ContraindicacaoRequest {
    'medicamentoId'?: JsonNullableUUID;
    'principioAtivoId'?: JsonNullableUUID;
    'especieId': string;
    'referenciaId'?: JsonNullableUUID;
    'referenciaTexto'?: string;
    'gravidade': ContraindicacaoRequestGravidadeEnum;
    'descricao': string;
}

export const ContraindicacaoRequestGravidadeEnum = {
    Leve: 'LEVE',
    Moderada: 'MODERADA',
    Grave: 'GRAVE',
    Fatal: 'FATAL'
} as const;

export type ContraindicacaoRequestGravidadeEnum = typeof ContraindicacaoRequestGravidadeEnum[keyof typeof ContraindicacaoRequestGravidadeEnum];


