/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JsonNullableDouble } from './json-nullable-double';
// May contain unused imports in some cases
// @ts-ignore
import type { JsonNullableUUID } from './json-nullable-uuid';

export interface DosagemItemRequest {
    'medicamentoId'?: JsonNullableUUID;
    'medicamentoTexto'?: string;
    'doseMinima'?: JsonNullableDouble;
    'doseMaxima'?: JsonNullableDouble;
    'unidade'?: string;
    'frequencia'?: string;
    'duracao'?: string;
    'via'?: string;
}

