/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface EspecieResponse {
    'id'?: string;
    'nomePopular'?: string;
    'nomeCientifico'?: string;
    'familiaTaxonomica'?: string;
    'grupo'?: string;
    'resumoClinico'?: string;
    'parametrosFisiologicos'?: string;
    'expectativaVida'?: string;
    'pesoAdulto'?: string;
    'tipoDieta'?: string;
    'manejoInfos'?: string;
    'receitaManejoPadrao'?: string;
    'alertasClinicos'?: string;
    'pontosExameFisico'?: string;
    'habitat'?: string;
    'distribuicaoGeografica'?: string;
    'statusConservacao'?: string;
    'bibliografiaBase'?: string;
    'criadoEm'?: string;
}

