/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface EspecieRequest {
    'nomePopular': string;
    'nomeCientifico': string;
    'familiaTaxonomica'?: string;
    'grupo'?: string;
    /**
     * Visão geral rápida para o clínico.
     */
    'resumoClinico'?: string;
    /**
     * FC, FR, Temp (Markdown)
     */
    'parametrosFisiologicos'?: string;
    'expectativaVida'?: string;
    'pesoAdulto'?: string;
    'tipoDieta'?: string;
    /**
     * Erros comuns de manejo
     */
    'manejoInfos'?: string;
    /**
     * 8 pilares de manejo pré-preenchidos
     */
    'receitaManejoPadrao'?: string;
    /**
     * Sensibilidades a medicamentos
     */
    'alertasClinicos'?: string;
    /**
     * O que não esquecer no exame
     */
    'pontosExameFisico'?: string;
    'habitat'?: string;
    'distribuicaoGeografica'?: string;
    'statusConservacao'?: string;
    'bibliografiaBase'?: string;
}

