/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface EventoAuditoriaRequest {
    'acao': EventoAuditoriaRequestAcaoEnum;
    'entidade': string;
    'idAlvo': string;
    'descricao': string;
    /**
     * JSON stringificado opcional
     */
    'metadados'?: string;
}

export const EventoAuditoriaRequestAcaoEnum = {
    PdfReceitaGerado: 'PDF_RECEITA_GERADO',
    PdfManejoGerado: 'PDF_MANEJO_GERADO',
    PdfProntuarioGerado: 'PDF_PRONTUARIO_GERADO',
    VisualizouProntuario: 'VISUALIZOU_PRONTUARIO'
} as const;

export type EventoAuditoriaRequestAcaoEnum = typeof EventoAuditoriaRequestAcaoEnum[keyof typeof EventoAuditoriaRequestAcaoEnum];


