/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PacienteRequest {
    'veterinarioId': string;
    'especieId': string;
    'nome': string;
    'dadosTutor': string;
    'identificacaoAnimal'?: string;
    'microchip'?: string;
    'pelagemCor'?: string;
    'sexo'?: PacienteRequestSexoEnum;
    'dataNascimento'?: string;
    'pesoAtualGramas'?: number;
}

export const PacienteRequestSexoEnum = {
    Macho: 'MACHO',
    Femea: 'FEMEA',
    Indefinido: 'INDEFINIDO'
} as const;

export type PacienteRequestSexoEnum = typeof PacienteRequestSexoEnum[keyof typeof PacienteRequestSexoEnum];


