/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PacienteResponse {
    'id'?: string;
    'nome'?: string;
    'especieId'?: string;
    'dadosTutor'?: string;
    'identificacaoAnimal'?: string;
    'pesoAtualGramas'?: number;
    'criadoEm'?: string;
    'veterinarioId'?: string;
    'dataNascimento'?: string;
    'microchip'?: string;
    'pelagemCor'?: string;
    'sexo'?: PacienteResponseSexoEnum;
}

export const PacienteResponseSexoEnum = {
    Macho: 'MACHO',
    Femea: 'FEMEA',
    Indefinido: 'INDEFINIDO'
} as const;

export type PacienteResponseSexoEnum = typeof PacienteResponseSexoEnum[keyof typeof PacienteResponseSexoEnum];


