/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DosagemResponse } from './dosagem-response';

export interface ProtocoloDetalhadoResponse {
    'id'?: string;
    'titulo'?: string;
    'referenciaTexto'?: string;
    'referenciaId'?: string;
    'observacoes'?: string;
    'origem'?: ProtocoloDetalhadoResponseOrigemEnum;
    'autorId'?: string;
    'dosagens'?: Array<DosagemResponse>;
    'alertasGerais'?: Array<string>;
}

export const ProtocoloDetalhadoResponseOrigemEnum = {
    Oficial: 'OFICIAL',
    Proprio: 'PROPRIO',
    Institucional: 'INSTITUCIONAL'
} as const;

export type ProtocoloDetalhadoResponseOrigemEnum = typeof ProtocoloDetalhadoResponseOrigemEnum[keyof typeof ProtocoloDetalhadoResponseOrigemEnum];


