/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DosagemItemRequest } from './dosagem-item-request';
// May contain unused imports in some cases
// @ts-ignore
import type { JsonNullableUUID } from './json-nullable-uuid';

export interface ProtocoloRequest {
    'titulo': string;
    'doencaId'?: JsonNullableUUID;
    'doencaTexto'?: string;
    'referenciaId'?: JsonNullableUUID;
    'referenciaTexto'?: string;
    'observacoes'?: string;
    'origem'?: ProtocoloRequestOrigemEnum;
    'autorId'?: string;
    'clinicaId'?: JsonNullableUUID;
    'dosagens': Array<DosagemItemRequest>;
}

export const ProtocoloRequestOrigemEnum = {
    Oficial: 'OFICIAL',
    Proprio: 'PROPRIO',
    Institucional: 'INSTITUCIONAL'
} as const;

export type ProtocoloRequestOrigemEnum = typeof ProtocoloRequestOrigemEnum[keyof typeof ProtocoloRequestOrigemEnum];


