/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ProtocoloVacinalRequest {
    'especieId': string;
    'vacinaId': string;
    /**
     * Fonte científica ou legal que exige/recomenda esta vacina
     */
    'referenciaId': string;
    'idadeMinimaDias': number;
    /**
     * Se nulo ou zero, é dose única
     */
    'diasParaReforco'?: number;
    /**
     * Se é exigida por lei (IBAMA/MAPA)
     */
    'obrigatoria'?: boolean;
    'observacoes'?: string;
}

