/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SugestaoResponse {
    'id'?: string;
    'usuarioId'?: string;
    'tipo'?: SugestaoResponseTipoEnum;
    'status'?: SugestaoResponseStatusEnum;
    'conteudo'?: string;
    'criadoEm'?: string;
}

export const SugestaoResponseTipoEnum = {
    Especie: 'ESPECIE',
    Doenca: 'DOENCA',
    Protocolo: 'PROTOCOLO',
    Calculo: 'CALCULO',
    Outro: 'OUTRO'
} as const;

export type SugestaoResponseTipoEnum = typeof SugestaoResponseTipoEnum[keyof typeof SugestaoResponseTipoEnum];
export const SugestaoResponseStatusEnum = {
    Pendente: 'PENDENTE',
    EmAnalise: 'EM_ANALISE',
    Aprovada: 'APROVADA',
    Rejeitada: 'REJEITADA'
} as const;

export type SugestaoResponseStatusEnum = typeof SugestaoResponseStatusEnum[keyof typeof SugestaoResponseStatusEnum];


