/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UsuarioResponse {
    'id'?: string;
    'nome'?: string;
    'email'?: string;
    'perfil'?: UsuarioResponsePerfilEnum;
    'crmv'?: string;
    'scope'?: UsuarioResponseScopeEnum;
}

export const UsuarioResponsePerfilEnum = {
    AdminGlobal: 'ADMIN_GLOBAL',
    AdminGestor: 'ADMIN_GESTOR',
    AdminClinico: 'ADMIN_CLINICO',
    Veterinario: 'VETERINARIO',
    Estudante: 'ESTUDANTE'
} as const;

export type UsuarioResponsePerfilEnum = typeof UsuarioResponsePerfilEnum[keyof typeof UsuarioResponsePerfilEnum];
export const UsuarioResponseScopeEnum = {
    Global: 'GLOBAL',
    Tenant: 'TENANT'
} as const;

export type UsuarioResponseScopeEnum = typeof UsuarioResponseScopeEnum[keyof typeof UsuarioResponseScopeEnum];


